// WARNING: do not edit this file directly, it is generated dynamically from
// the source JSDOC comments using the npm run docs script.

import React from "react";



export const argTypes = {
  opts: {
    control: {},
    defaultValue: "{}",
    description: "Output size (required here or on the chart) and DOM options.",
    table: {
      defaultValue: {
        summary: "{}"
      }
    },
    type: {
      required: false,
      summary: "staticrenderoptions"
    }
  },
  viz: {
    control: {},
    description: "A configured chart instance (data + accessors already set).",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: true,
      summary: "renderableviz"
    }
  }
};
