// WARNING: do not edit this file directly, it is generated dynamically from
// the source JSDOC comments using the npm run docs script.

import React from "react";



export const argTypes = {
  callback: {
    control: {},
    description: "A function that is called when the final data is loaded. It is passed 2 variables, any error present and the data loaded.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "function"
    }
  },
  formatter: {
    control: {},
    description: "An optional formatter function that is run on the loaded data.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "function"
    }
  },
  key: {
    control: {
      type: "text"
    },
    description: "The key in the `this` context to save the resulting data to.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "string"
    }
  },
  path: {
    control: {
      type: "object"
    },
    description: "The path to the file or url to be loaded. Also support array of paths strings. If an Array of objects is passed, the xhr request logic is skipped.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: true,
      summary: "array | string"
    }
  }
};
