// WARNING: do not edit this file directly, it is generated dynamically from
// the source JSDOC comments using the npm run docs script.

import React from "react";



export const argTypes = {
  arrayOfArray: {
    control: {
      type: "object"
    },
    description: "Array of elements",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: true,
      summary: "array"
    }
  },
  data: {
    control: {
      type: "text"
    },
    defaultValue: "\"data\"",
    description: "The key used for the flat data array if exists inside of the JSON object.",
    table: {
      defaultValue: {
        summary: "\"data\""
      }
    },
    type: {
      required: false,
      summary: "string"
    }
  }
};
