// WARNING: do not edit this file directly, it is generated dynamically from
// the source JSDOC comments using the npm run docs script.

import React from "react";



export const argTypes = {
  data: {
    control: {
      type: "text"
    },
    defaultValue: "\"data\"",
    description: "The key used for the flat data array inside of the JSON object.",
    table: {
      defaultValue: {
        summary: "\"data\""
      }
    },
    type: {
      required: false,
      summary: "string"
    }
  },
  headers: {
    control: {
      type: "text"
    },
    defaultValue: "\"headers\"",
    description: "The key used for the flat headers array inside of the JSON object.",
    table: {
      defaultValue: {
        summary: "\"headers\""
      }
    },
    type: {
      required: false,
      summary: "string"
    }
  },
  json: {
    control: {
      type: "object"
    },
    description: "A JSON data Object with `data` and `headers` keys.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: true,
      summary: "object"
    }
  }
};
