// WARNING: do not edit this file directly, it is generated dynamically from
// the source JSDOC comments using the npm run docs script.

import React from "react";



export const argTypes = {
  aggs: {
    control: {
      type: "object"
    },
    description: "An object containing specific aggregation methods (functions) for each key type. By default, numbers are summed and strings are returned as an array of unique values.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: true,
      summary: "object"
    }
  },
  objects: {
    control: {
      type: "object"
    },
    description: "The Array of objects to be merged together.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: true,
      summary: "array"
    }
  }
};
