// WARNING: do not edit this file directly, it is generated dynamically from
// the source JSDOC comments using the npm run docs script.

import React from "react";



export const argTypes = {
  data: {
    control: {},
    description: "The flat data array to nest.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: true,
      summary: "array.&lt;datapoint&gt;"
    }
  },
  fns: {
    control: {},
    description: "An array of key accessor functions, one per nesting level.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: true,
      summary: "array.&lt;keyaccessor&gt;"
    }
  }
};
