// WARNING: do not edit this file directly, it is generated dynamically from
// the source JSDOC comments using the npm run docs script.

import React from "react";



export const argTypes = {
  callback: {
    control: {},
    description: "A function to be invoked at the end of each render cycle (passed directly to the render method).",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "function"
    }
  },
  className: {
    control: {
      type: "text"
    },
    defaultValue: "\"renderer\"",
    description: "The class attribute value used for the root/wrapper <div> element.",
    table: {
      defaultValue: {
        summary: "\"renderer\""
      }
    },
    type: {
      required: false,
      summary: "string"
    }
  },
  config: {
    control: {
      type: "object"
    },
    description: "An object containing method/value pairs to be passed to the visualization's .config( ) method.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: true,
      summary: "object"
    }
  }
};
