coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto

flag_management:
  default_rules:
    carryforward: true
    statuses:
      - type: project
        target: auto
        threshold: 1%
      - type: patch
        target: auto
  individual_flags:
    - name: color
      paths:
        - packages/color/
      statuses:
        - type: project
          target: 95%
    - name: core
      paths:
        - packages/core/
      statuses:
        - type: project
          target: 25%
    - name: data
      paths:
        - packages/data/
      statuses:
        - type: project
          target: 95%
    - name: dom
      paths:
        - packages/dom/
      statuses:
        - type: project
          target: 95%
    - name: export
      paths:
        - packages/export/
      statuses:
        - type: project
          target: 40%
    - name: format
      paths:
        - packages/format/
      statuses:
        - type: project
          target: 70%
    - name: locales
      paths:
        - packages/locales/
      statuses:
        - type: project
          target: 95%
    - name: math
      paths:
        - packages/math/
      statuses:
        - type: project
          target: 80%
    - name: react
      paths:
        - packages/react/
      statuses:
        - type: project
          target: 65%
    - name: text
      paths:
        - packages/text/
      statuses:
        - type: project
          target: 85%
