// WARNING: do not edit this file directly, it is generated dynamically from
// the source JSDOC comments using the npm run docs script.

import React from "react";



export const argTypes = {
  c: {
    control: {
      type: "text"
    },
    description: "A valid CSS color string.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: true,
      summary: "string"
    }
  },
  i: {
    control: {
      type: "text"
    },
    defaultValue: 0.5,
    description: "A value from 0 to 1 dictating the strength of the function.",
    table: {
      defaultValue: {
        summary: 0.5
      }
    },
    type: {
      required: false,
      summary: "string"
    }
  }
};
