// WARNING: do not edit this file directly, it is generated dynamically from
// the source JSDOC comments using the npm run docs script.

import React from "react";
import {argTypes as baseClassArgTypes} from "../utils/BaseClass.args.jsx";
import {assign} from "@d3plus/dom";

import {Box as D3plusBox} from "@d3plus/react";
export const Box = ({ config }) => <D3plusBox config={config} />;

export const argTypes = assign(

  /**
   * Filters out unused argTypes from the BaseClass primitive and
   * overrides any defaults that have been changed in Box
   */
  Object.keys(baseClassArgTypes)
    .reduce((obj, k) => (obj[k] = baseClassArgTypes[k], obj), {}),

  /**
   * Box-specific methods
   */
  
  {
    active: {
      control: {},
      description: "The active highlight state for all sub-shapes in this Box.",
      table: {
        defaultValue: {
          summary: "undefined"
        }
      },
      type: {
        required: true,
        summary: "function | null"
      }
    },
    config: {
      control: {},
      description: "Narrowed `.config()` for Box. Inherited surface from\n`BaseClass.config()`; the override exists only to surface per-shape\nkeys (e.g. `width`/`height` for Rect) in autocomplete + type checks.",
      table: {
        defaultValue: {
          summary: "undefined"
        }
      },
      type: {
        required: true,
        summary: "partial"
      }
    },
    data: {
      control: {},
      description: "The data array used to create shapes.",
      table: {
        defaultValue: {
          summary: "undefined"
        }
      },
      type: {
        required: true,
        summary: "array.&lt;datapoint&gt;"
      }
    },
    hover: {
      control: {},
      description: "The hover highlight state for all sub-shapes in this Box.",
      table: {
        defaultValue: {
          summary: "undefined"
        }
      },
      type: {
        required: true,
        summary: "function | null"
      }
    },
    locale: {
      control: {
        type: "object"
      },
      description: "The locale used for all text and number formatting. Supports the locales defined in [d3plus-format](https://github.com/d3plus/d3plus-format/blob/master/src/locale.js). The locale can be a complex Object, a locale code (like \"en-US\"), or a 2-digit language code (like \"en\"). If a 2-digit code is provided, the \"findLocale\" function is used to identify the most approximate locale.",
      table: {
        defaultValue: {
          summary: "undefined"
        }
      },
      type: {
        required: true,
        summary: "string | object"
      }
    },
    medianConfig: {
      control: {},
      description: "Configuration object for the median line.",
      table: {
        defaultValue: {
          summary: "undefined"
        }
      },
      type: {
        required: true,
        summary: "record"
      }
    },
    on: {
      control: {
        type: "text"
      },
      description: "Event listener for the specified event *typenames*. Mirrors the core [d3-selection](https://github.com/d3/d3-selection#selection_on) behavior.",
      table: {
        defaultValue: {
          summary: "undefined"
        }
      },
      type: {
        required: true,
        summary: "string"
      }
    },
    orient: {
      control: {},
      description: "Orientation: \"vertical\" or \"horizontal\".",
      table: {
        defaultValue: {
          summary: "undefined"
        }
      },
      type: {
        required: false,
        summary: "constoraccessor"
      }
    },
    outlier: {
      control: {},
      description: "Outlier accessor (per-datum predicate).",
      table: {
        defaultValue: {
          summary: "undefined"
        }
      },
      type: {
        required: false,
        summary: "constoraccessor"
      }
    },
    outlierConfig: {
      control: {},
      description: "Configuration object for each outlier point.",
      table: {
        defaultValue: {
          summary: "undefined"
        }
      },
      type: {
        required: true,
        summary: "record"
      }
    },
    parent: {
      control: {},
      description: "Parent config used by the wrapper.",
      table: {
        defaultValue: {
          summary: "undefined"
        }
      },
      type: {
        required: true,
        summary: "unknown"
      }
    },
    rectConfig: {
      control: {},
      description: "Configuration object for the rect shape.",
      table: {
        defaultValue: {
          summary: "undefined"
        }
      },
      type: {
        required: true,
        summary: "record"
      }
    },
    rectWidth: {
      control: {},
      description: "",
      table: {
        defaultValue: {
          summary: "undefined"
        }
      },
      type: {
        required: false,
        summary: "constoraccessor"
      }
    },
    select: {
      control: {
        type: "text"
      },
      description: "The SVG container element for this visualization. 3 selector or DOM element.",
      table: {
        defaultValue: {
          summary: "undefined"
        }
      },
      type: {
        required: true,
        summary: "string | htmlelement | svgelement | null"
      }
    },
    shapeConfig: {
      control: {},
      description: "Configuration object with key/value pairs applied as method calls on each shape.",
      table: {
        defaultValue: {
          summary: "undefined"
        }
      },
      type: {
        required: true,
        summary: "d3plusconfig"
      }
    },
    translate: {
      control: {},
      description: "Defines how informational text strings should be displayed. By default, this function will try to find the string in question (which is the first argument provided to this function) inside of an internally managed translation Object. If you'd like to override to use custom text, simply pass this method your own custom formatting function.",
      table: {
        defaultValue: {
          summary: "undefined"
        }
      },
      type: {
        required: true,
        summary: "function"
      }
    },
    whiskerConfig: {
      control: {},
      description: "Configuration object for the whisker.",
      table: {
        defaultValue: {
          summary: "undefined"
        }
      },
      type: {
        required: true,
        summary: "record"
      }
    },
    whiskerMode: {
      control: {
        type: "object"
      },
      defaultValue: [
        "tukey",
        "tukey"
      ],
      description: "Whisker mode: single mode string/number or [low, high] pair.",
      table: {
        defaultValue: {
          summary: "[\"tukey\",\"tukey\"]"
        }
      },
      type: {
        required: false,
        summary: "string | number | array.&lt;string | number&gt;"
      }
    },
    x: {
      control: {},
      description: "",
      table: {
        defaultValue: {
          summary: "undefined"
        }
      },
      type: {
        required: false,
        summary: "constoraccessor"
      }
    },
    y: {
      control: {},
      description: "",
      table: {
        defaultValue: {
          summary: "undefined"
        }
      },
      type: {
        required: false,
        summary: "constoraccessor"
      }
    }
  }
);
