// WARNING: do not edit this file directly, it is generated dynamically from
// the source JSDOC comments using the npm run docs script.

import React from "react";
import {argTypes as shapeArgTypes} from "./Shape.args.jsx";
import {assign} from "@d3plus/dom";

import {Circle as D3plusCircle} from "@d3plus/react";
export const Circle = ({ config }) => <D3plusCircle config={config} />;

export const argTypes = assign(

  /**
   * Filters out unused argTypes from the Shape primitive and
   * overrides any defaults that have been changed in Circle
   */
  Object.keys(shapeArgTypes)
    .reduce((obj, k) => (obj[k] = shapeArgTypes[k], obj), {}),

  /**
   * Circle-specific methods
   */
  
  {
    labelBounds: {
      control: {},
      defaultValue: "(d, i, s) => ({width: s.r * 1.5, height: s.r * 1.5, x: -s.r * 0.75, y: -s.r * 0.75})",
      description: "The given function is passed the data point, index, and internally defined properties of the shape and should return an object containing the following values: `width`, `height`, `x`, `y`. If an array is returned from the function, each value will be used in conjunction with each label.",
      table: {
        defaultValue: {
          detail: "(d, i, s) => ({width: s.r * 1.5, height: s.r * 1.5, x: -s.r * 0.75, y: -s.r * 0.75})",
          summary: "function"
        }
      },
      type: {
        required: false,
        summary: "function"
      }
    },
    labelConfig: {
      control: {
        type: "object"
      },
      defaultValue: "assign(this._labelConfig, {textAnchor: middle, verticalAlign: middle})",
      table: {
        defaultValue: {
          summary: "assign(this._labelConfig, {textAnchor: middle, verticalAlign: middle})"
        }
      },
      type: {
        required: false,
        summary: "object"
      }
    },
    r: {
      control: {
        type: "number"
      },
      defaultValue: "d => d[\"r\"]",
      table: {
        defaultValue: {
          detail: "d => d[\"r\"]",
          summary: "function"
        }
      },
      type: {
        required: false,
        summary: "function | number"
      }
    },
    render: {
      control: {},
      table: {
        defaultValue: {
          summary: "undefined"
        }
      },
      type: {
        required: false,
        summary: "function"
      }
    }
  }
);
