// WARNING: do not edit this file directly, it is generated dynamically from
// the source JSDOC comments using the npm run docs script.

import React from "react";

import {Image as D3plusImage} from "@d3plus/react";
export const Image = ({ config }) => <D3plusImage config={config} />;

export const argTypes = {
  data: {
    control: {
      type: "array"
    },
    defaultValue: "[]",
    table: {
      defaultValue: {
        summary: "[]"
      }
    },
    type: {
      required: false,
      summary: "array"
    }
  },
  duration: {
    control: {
      type: "number"
    },
    defaultValue: 600,
    table: {
      defaultValue: {
        summary: 600
      }
    },
    type: {
      required: false,
      summary: "number"
    }
  },
  height: {
    control: {
      type: "number"
    },
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "function | number"
    }
  },
  id: {
    control: {},
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "function"
    }
  },
  opacity: {
    control: {
      type: "number"
    },
    defaultValue: 1,
    table: {
      defaultValue: {
        summary: 1
      }
    },
    type: {
      required: false,
      summary: "number"
    }
  },
  pointerEvents: {
    control: {
      type: "text"
    },
    defaultValue: "\"auto\"",
    table: {
      defaultValue: {
        summary: "\"auto\""
      }
    },
    type: {
      required: false,
      summary: "function | string"
    }
  },
  render: {
    control: {},
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "function"
    }
  },
  select: {
    control: {
      type: "text"
    },
    defaultValue: "d3.select(\"body\").append(\"svg\")",
    table: {
      defaultValue: {
        summary: "d3.select(\"body\").append(\"svg\")"
      }
    },
    type: {
      required: false,
      summary: "string | htmlelement"
    }
  },
  url: {
    control: {},
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "function"
    }
  },
  width: {
    control: {
      type: "number"
    },
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "function | number"
    }
  },
  x: {
    control: {
      type: "number"
    },
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "function | number"
    }
  },
  y: {
    control: {
      type: "number"
    },
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "function | number"
    }
  }
};
