// WARNING: do not edit this file directly, it is generated dynamically from
// the source JSDOC comments using the npm run docs script.

import React from "react";

import {Image as D3plusImage} from "@d3plus/react";
export const Image = ({ config }) => <D3plusImage config={config} />;

export const argTypes = {
  render: {
    control: {},
    description: "Renders the current Image to the page. If a *callback* is specified, it will be called once the images are done drawing.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "function"
    }
  }
};
