// WARNING: do not edit this file directly, it is generated dynamically from
// the source JSDOC comments using the npm run docs script.

import React from "react";
import {argTypes as shapeArgTypes} from "./Shape.args.jsx";
import {assign} from "@d3plus/dom";

import {Rect as D3plusRect} from "@d3plus/react";
export const Rect = ({ config }) => <D3plusRect config={config} />;

export const argTypes = assign(

  /**
   * Filters out unused argTypes from the Shape primitive and
   * overrides any defaults that have been changed in Rect
   */
  Object.keys(shapeArgTypes)
    .reduce((obj, k) => (obj[k] = shapeArgTypes[k], obj), {}),

  /**
   * Rect-specific methods
   */
  
  {
    height: {
      control: {
        type: "number"
      },
      defaultValue: "d => d[\"height\"]",
      description: "If *value* is specified, sets the height accessor to the specified function or number and returns the current class instance.",
      table: {
        defaultValue: {
          detail: "d => d[\"height\"]",
          summary: "function"
        }
      },
      type: {
        required: false,
        summary: "function | number"
      }
    },
    labelBounds: {
      control: {},
      defaultValue: "(d, i, s) => ({width: s.width, height: s.height, x: -s.width / 2, y: -s.height / 2})",
      description: "If *bounds* is specified, sets the label bounds to the specified function and returns the current class instance. If *bounds* is not specified, returns the current inner bounds accessor.",
      table: {
        defaultValue: {
          detail: "(d, i, s) => ({width: s.width, height: s.height, x: -s.width / 2, y: -s.height / 2})",
          summary: "function"
        }
      },
      type: {
        required: false,
        summary: "function"
      }
    },
    render: {
      control: {},
      description: "Draws the rectangles.",
      table: {
        defaultValue: {
          summary: "undefined"
        }
      },
      type: {
        required: false,
        summary: "function"
      }
    },
    width: {
      control: {
        type: "number"
      },
      defaultValue: "d => d[\"width\"]",
      description: "If *value* is specified, sets the width accessor to the specified function or number and returns the current class instance.",
      table: {
        defaultValue: {
          detail: "d => d[\"width\"]",
          summary: "function"
        }
      },
      type: {
        required: false,
        summary: "function | number"
      }
    }
  }
);
