// WARNING: do not edit this file directly, it is generated dynamically from
// the source JSDOC comments using the npm run docs script.

import React from "react";
import {argTypes as baseClassArgTypes} from "../utils/BaseClass.args.jsx";
import {assign} from "@d3plus/dom";

import {Shape as D3plusShape} from "@d3plus/react";
export const Shape = ({ config }) => <D3plusShape config={config} />;

export const argTypes = assign(

  /**
   * Filters out unused argTypes from the BaseClass primitive and
   * overrides any defaults that have been changed in Shape
   */
  Object.keys(baseClassArgTypes)
    .reduce((obj, k) => (obj[k] = baseClassArgTypes[k], obj), {}),

  /**
   * Shape-specific methods
   */
  
  {
    _dataFilter: {
      control: {},
      description: "",
      table: {
        defaultValue: {
          summary: "undefined"
        }
      },
      type: {
        required: true,
        summary: "array.&lt;datapoint&gt;"
      }
    },
    active: {
      control: {},
      description: "The active callback function for highlighting shapes.",
      table: {
        defaultValue: {
          summary: "undefined"
        }
      },
      type: {
        required: true,
        summary: "function | null"
      }
    },
    activeOpacity: {
      control: {
        type: "number"
      },
      defaultValue: 0.25,
      description: "",
      table: {
        defaultValue: {
          summary: "0.25"
        }
      },
      type: {
        required: false,
        summary: "number"
      }
    },
    activeStyle: {
      control: {},
      description: "The style to apply to active shapes.",
      table: {
        defaultValue: {
          summary: "undefined"
        }
      },
      type: {
        required: true,
        summary: "record"
      }
    },
    ariaLabel: {
      control: {},
      description: "",
      table: {
        defaultValue: {
          summary: "undefined"
        }
      },
      type: {
        required: false,
        summary: "function"
      }
    },
    backgroundImage: {
      control: {},
      description: "",
      table: {
        defaultValue: {
          summary: "undefined"
        }
      },
      type: {
        required: false,
        summary: "function"
      }
    },
    config: {
      control: {},
      description: "Narrowed `.config()` for Shape. Inherited surface from\n`BaseClass.config()`; the override exists only to surface per-shape\nkeys (e.g. `width`/`height` for Rect) in autocomplete + type checks.",
      table: {
        defaultValue: {
          summary: "undefined"
        }
      },
      type: {
        required: true,
        summary: "partial"
      }
    },
    data: {
      control: {},
      defaultValue: "[  ]",
      description: "The data array used to create shapes. A shape will be drawn for each object in the array.",
      table: {
        defaultValue: {
          summary: "[  ]"
        }
      },
      type: {
        required: true,
        summary: "array.&lt;datapoint&gt;"
      }
    },
    discrete: {
      control: {},
      description: "",
      table: {
        defaultValue: {
          summary: "undefined"
        }
      },
      type: {
        required: false,
        summary: "unknown"
      }
    },
    duration: {
      control: {
        type: "number"
      },
      defaultValue: 600,
      description: "",
      table: {
        defaultValue: {
          summary: "600"
        }
      },
      type: {
        required: false,
        summary: "number"
      }
    },
    fill: {
      control: {},
      description: "",
      table: {
        defaultValue: {
          summary: "undefined"
        }
      },
      type: {
        required: false,
        summary: "function"
      }
    },
    fillOpacity: {
      control: {},
      description: "",
      table: {
        defaultValue: {
          summary: "undefined"
        }
      },
      type: {
        required: false,
        summary: "function"
      }
    },
    hitArea: {
      control: {},
      description: "",
      table: {
        defaultValue: {
          summary: "undefined"
        }
      },
      type: {
        required: false,
        summary: "unknown"
      }
    },
    hover: {
      control: {},
      description: "The hover callback function for highlighting shapes on mouseover.",
      table: {
        defaultValue: {
          summary: "undefined"
        }
      },
      type: {
        required: true,
        summary: "function | null"
      }
    },
    hoverOpacity: {
      control: {
        type: "number"
      },
      defaultValue: 0.5,
      description: "",
      table: {
        defaultValue: {
          summary: "0.5"
        }
      },
      type: {
        required: false,
        summary: "number"
      }
    },
    hoverStyle: {
      control: {},
      description: "The style to apply to hovered shapes.",
      table: {
        defaultValue: {
          summary: "undefined"
        }
      },
      type: {
        required: true,
        summary: "record"
      }
    },
    id: {
      control: {},
      description: "",
      table: {
        defaultValue: {
          summary: "undefined"
        }
      },
      type: {
        required: false,
        summary: "function"
      }
    },
    label: {
      control: {},
      description: "",
      table: {
        defaultValue: {
          summary: "undefined"
        }
      },
      type: {
        required: false,
        summary: "function"
      }
    },
    labelBounds: {
      control: {},
      description: "",
      table: {
        defaultValue: {
          summary: "undefined"
        }
      },
      type: {
        required: false,
        summary: "unknown"
      }
    },
    labelConfig: {
      control: {},
      description: "A pass-through to the config method of the TextBox class used to create a shape's labels.",
      table: {
        defaultValue: {
          summary: "undefined"
        }
      },
      type: {
        required: true,
        summary: "record"
      }
    },
    locale: {
      control: {
        type: "object"
      },
      description: "The locale used for all text and number formatting. Supports the locales defined in [d3plus-format](https://github.com/d3plus/d3plus-format/blob/master/src/locale.js). The locale can be a complex Object, a locale code (like \"en-US\"), or a 2-digit language code (like \"en\"). If a 2-digit code is provided, the \"findLocale\" function is used to identify the most approximate locale.",
      table: {
        defaultValue: {
          summary: "undefined"
        }
      },
      type: {
        required: true,
        summary: "string | object"
      }
    },
    on: {
      control: {
        type: "text"
      },
      description: "Event listener for the specified event *typenames*. Mirrors the core [d3-selection](https://github.com/d3/d3-selection#selection_on) behavior.",
      table: {
        defaultValue: {
          summary: "undefined"
        }
      },
      type: {
        required: true,
        summary: "string"
      }
    },
    opacity: {
      control: {},
      description: "",
      table: {
        defaultValue: {
          summary: "undefined"
        }
      },
      type: {
        required: false,
        summary: "function"
      }
    },
    parent: {
      control: {},
      description: "Parent config used by the wrapper.",
      table: {
        defaultValue: {
          summary: "undefined"
        }
      },
      type: {
        required: true,
        summary: "unknown"
      }
    },
    pointerEvents: {
      control: {},
      description: "",
      table: {
        defaultValue: {
          summary: "undefined"
        }
      },
      type: {
        required: false,
        summary: "function"
      }
    },
    role: {
      control: {},
      description: "",
      table: {
        defaultValue: {
          summary: "undefined"
        }
      },
      type: {
        required: false,
        summary: "function"
      }
    },
    rotate: {
      control: {},
      description: "",
      table: {
        defaultValue: {
          summary: "undefined"
        }
      },
      type: {
        required: false,
        summary: "function"
      }
    },
    rx: {
      control: {},
      description: "",
      table: {
        defaultValue: {
          summary: "undefined"
        }
      },
      type: {
        required: false,
        summary: "function"
      }
    },
    ry: {
      control: {},
      description: "",
      table: {
        defaultValue: {
          summary: "undefined"
        }
      },
      type: {
        required: false,
        summary: "function"
      }
    },
    scale: {
      control: {},
      description: "",
      table: {
        defaultValue: {
          summary: "undefined"
        }
      },
      type: {
        required: false,
        summary: "function"
      }
    },
    select: {
      control: {
        type: "text"
      },
      description: "The SVG container element as a d3 selector or DOM element.",
      table: {
        defaultValue: {
          summary: "undefined"
        }
      },
      type: {
        required: true,
        summary: "string | htmlelement | svgelement | null"
      }
    },
    shapeConfig: {
      control: {},
      description: "Configuration object with key/value pairs applied as method calls on each shape.",
      table: {
        defaultValue: {
          summary: "undefined"
        }
      },
      type: {
        required: true,
        summary: "d3plusconfig"
      }
    },
    shapeRendering: {
      control: {},
      description: "",
      table: {
        defaultValue: {
          summary: "undefined"
        }
      },
      type: {
        required: false,
        summary: "function"
      }
    },
    sort: {
      control: {},
      description: "A comparator function used to sort shapes for layering order.",
      table: {
        defaultValue: {
          summary: "undefined"
        }
      },
      type: {
        required: true,
        summary: "function | null"
      }
    },
    stroke: {
      control: {},
      description: "",
      table: {
        defaultValue: {
          summary: "undefined"
        }
      },
      type: {
        required: false,
        summary: "function"
      }
    },
    strokeDasharray: {
      control: {},
      description: "",
      table: {
        defaultValue: {
          summary: "undefined"
        }
      },
      type: {
        required: false,
        summary: "function"
      }
    },
    strokeLinecap: {
      control: {},
      description: "",
      table: {
        defaultValue: {
          summary: "undefined"
        }
      },
      type: {
        required: false,
        summary: "function"
      }
    },
    strokeOpacity: {
      control: {},
      description: "",
      table: {
        defaultValue: {
          summary: "undefined"
        }
      },
      type: {
        required: false,
        summary: "function"
      }
    },
    strokeWidth: {
      control: {},
      description: "",
      table: {
        defaultValue: {
          summary: "undefined"
        }
      },
      type: {
        required: false,
        summary: "function"
      }
    },
    textAnchor: {
      control: {},
      description: "",
      table: {
        defaultValue: {
          summary: "undefined"
        }
      },
      type: {
        required: false,
        summary: "function"
      }
    },
    texture: {
      control: {},
      description: "",
      table: {
        defaultValue: {
          summary: "undefined"
        }
      },
      type: {
        required: false,
        summary: "function"
      }
    },
    textureDefault: {
      control: {},
      description: "A series of global texture methods to be used for all textures (ie. `{stroke: \"darkorange\", strokeWidth: 2}`).",
      table: {
        defaultValue: {
          summary: "undefined"
        }
      },
      type: {
        required: true,
        summary: "record"
      }
    },
    translate: {
      control: {},
      description: "Defines how informational text strings should be displayed. By default, this function will try to find the string in question (which is the first argument provided to this function) inside of an internally managed translation Object. If you'd like to override to use custom text, simply pass this method your own custom formatting function.",
      table: {
        defaultValue: {
          summary: "undefined"
        }
      },
      type: {
        required: true,
        summary: "function"
      }
    },
    vectorEffect: {
      control: {},
      description: "",
      table: {
        defaultValue: {
          summary: "undefined"
        }
      },
      type: {
        required: false,
        summary: "function"
      }
    },
    verticalAlign: {
      control: {},
      description: "",
      table: {
        defaultValue: {
          summary: "undefined"
        }
      },
      type: {
        required: false,
        summary: "function"
      }
    },
    x: {
      control: {},
      description: "",
      table: {
        defaultValue: {
          summary: "undefined"
        }
      },
      type: {
        required: false,
        summary: "function"
      }
    },
    y: {
      control: {},
      description: "",
      table: {
        defaultValue: {
          summary: "undefined"
        }
      },
      type: {
        required: false,
        summary: "function"
      }
    }
  }
);
