// WARNING: do not edit this file directly, it is generated dynamically from
// the source JSDOC comments using the npm run docs script.

import React from "react";



export const argTypes = {
  data: {
    control: {},
    description: "",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: true,
      summary: "array.&lt;number&gt;"
    }
  },
  nClusters: {
    control: {
      type: "number"
    },
    description: "",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: true,
      summary: "number"
    }
  }
};
