// WARNING: do not edit this file directly, it is generated dynamically from
// the source JSDOC comments using the npm run docs script.

import React from "react";



export const argTypes = {
  highestQuality: {
    control: {
      type: "boolean"
    },
    defaultValue: false,
    description: "Excludes distance-based preprocessing step which leads to highest quality simplification but runs ~10-20 times slower.",
    table: {
      defaultValue: {
        summary: false
      }
    },
    type: {
      required: false,
      summary: "boolean"
    }
  },
  poly: {
    control: {
      type: "array"
    },
    description: "An Array of points that represent a polygon.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: true,
      summary: "array"
    }
  },
  tolerance: {
    control: {
      type: "number"
    },
    defaultValue: 1,
    description: "Affects the amount of simplification (in the same metric as the point coordinates).",
    table: {
      defaultValue: {
        summary: 1
      }
    },
    type: {
      required: false,
      summary: "number"
    }
  }
};
