// WARNING: do not edit this file directly, it is generated dynamically from
// the source JSDOC comments using the npm run docs script.

import React from "react";



export const argTypes = {
  p1: {
    control: {},
    description: "The first point of the first line segment, which should always be an `[x, y]` formatted Array.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: true,
      summary: "point"
    }
  },
  p2: {
    control: {},
    description: "The first point of the second line segment, which should always be an `[x, y]` formatted Array.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: true,
      summary: "point"
    }
  },
  q1: {
    control: {},
    description: "The second point of the first line segment, which should always be an `[x, y]` formatted Array.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: true,
      summary: "point"
    }
  },
  q2: {
    control: {},
    description: "The second point of the second line segment, which should always be an `[x, y]` formatted Array.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: true,
      summary: "point"
    }
  }
};
