// WARNING: do not edit this file directly, it is generated dynamically from
// the source JSDOC comments using the npm run docs script.

import React from "react";



export const argTypes = {
  level: {
    control: {
      type: "number"
    },
    defaultValue: "0.95",
    description: "The confidence level, between 0 and 1. Defaults to 0.95.",
    table: {
      defaultValue: {
        summary: "0.95"
      }
    },
    type: {
      required: false,
      summary: "number"
    }
  },
  points: {
    control: {},
    description: "An array of `[x, y]` pairs.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: true,
      summary: "array.&lt;*&gt;"
    }
  }
};
