// WARNING: do not edit this file directly, it is generated dynamically from
// the source JSDOC comments using the npm run docs script.

import React from "react";



export const argTypes = {
  bounds: {
    control: {},
    description: "The region to search, such as a chart's plot area.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: true,
      summary: "bounds"
    }
  },
  obstacles: {
    control: {},
    description: "The bounding boxes of the marks drawn inside `bounds`.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: true,
      summary: "array.&lt;bounds&gt;"
    }
  },
  options: {
    control: {},
    defaultValue: "{}",
    description: "Padding and minimum-size options.",
    table: {
      defaultValue: {
        summary: "{}"
      }
    },
    type: {
      required: false,
      summary: "negativespaceoptions"
    }
  }
};
