// WARNING: do not edit this file directly, it is generated dynamically from
// the source JSDOC comments using the npm run docs script.

import React from "react";



export const argTypes = {
  options: {
    control: {},
    defaultValue: "{}",
    description: "Additional options, such as the polynomial `order`.",
    table: {
      defaultValue: {
        summary: "{}"
      }
    },
    type: {
      required: false,
      summary: "regressionoptions"
    }
  },
  points: {
    control: {},
    description: "An array of `[x, y]` pairs.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: true,
      summary: "array.&lt;*&gt;"
    }
  },
  type: {
    control: {},
    defaultValue: "linear",
    description: "The regression model: \"linear\", \"exponential\", \"logarithmic\", \"power\", or \"polynomial\".",
    table: {
      defaultValue: {
        summary: "linear"
      }
    },
    type: {
      required: false,
      summary: "regressiontype"
    }
  }
};
