// WARNING: do not edit this file directly, it is generated dynamically from
// the source JSDOC comments using the npm run docs script.

import React from "react";



export const argTypes = {
  df: {
    control: {
      type: "number"
    },
    description: "Degrees of freedom (greater than 0).",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: true,
      summary: "number"
    }
  },
  p: {
    control: {
      type: "number"
    },
    description: "A probability between 0 and 1 (e.g. 0.975 for a two-sided 95% interval).",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: true,
      summary: "number"
    }
  }
};
