// WARNING: do not edit this file directly, it is generated dynamically from
// the source JSDOC comments using the npm run docs script.

import React from "react";



export const argTypes = {
  def: {
    control: {},
    description: "A default value to be returned if the key is not present.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "*"
    }
  },
  key: {
    control: {
      type: "text"
    },
    description: "The key to be returned from each Object passed to the function.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: true,
      summary: "string"
    }
  }
};
