/**
    `ResolvedSpec` + `resolveSpec(viz)` — the boundary between
    "config the user supplied" and "context the pipeline transforms."

    Today the chart's class instance holds both: every `this._foo` slot is
    either a config the user can set (via accessors) or a derived value the
    pipeline writes back during `_preDraw` / `_draw` / `_paint`. The clean
    split is:

      ResolvedSpec     <- user config (frozen, immutable, serializable)
        ↓
      VizContext       <- pipeline-derived state (filteredData, drawDepth,
                          legendData, _chartScene, etc.)

    `resolveSpec(viz)` returns a frozen snapshot of every user-settable
    config key for the given viz instance. The free functions
    `vizPreDraw(viz)` / `vizDraw(viz)` / `runVizPipeline(viz)` /
    `plotPaint(viz, ctx)` all take a live viz instance — the
    contract that's currently shipping. `resolveSpec` is provided as a
    public seam so callers (custom drivers, tests, future refactors)
    can pin a config snapshot independently of any draw cycle. The
    spec type is the contract.

    The spec is a READONLY view: mutating it is a programming error. The
    type uses `Readonly<>` to discourage in-place writes; runtime
    freezing happens in `resolveSpec()`.
*/

import type {VizInstance} from "../viz/vizTypes.js";

/**
    All user-settable configuration keys on a chart, frozen.

    Generated by stripping the `_` prefix from every Viz/Plot/chart-subclass
    instance field that has a matching accessor method. Accessor reflection
    is handled by `BaseClass.config()`; this type is the static shape.

    A `Record<string, unknown>` keyed by config name — chart subclasses add
    their own fields and the `installFluent`-installed accessors don't carry
    static type info. As schemas gain types, this can narrow to per-field
    unions.
*/
export type ResolvedSpec = Readonly<Record<string, unknown>>;

/**
    Snapshot every config key from a viz instance into a frozen spec.

    Reads the same keys `BaseClass.config()` reflects — strips the `_`
    prefix from every instance field whose name matches a method on the
    prototype (the v3/v4 config-method-is-also-the-storage-slot pattern).
    Returns a frozen object so consumers can't accidentally mutate it
    upstream of the chart.
*/
export function resolveSpec(viz: VizInstance): ResolvedSpec {
  // BaseClass.config() already does this reflection; reuse it.
  const cfg = typeof viz.config === "function" ? viz.config() : {};
  // Object.freeze for shallow protection. Deep freeze isn't worth the cost
  // (most consumers don't mutate, and accessor functions reading the spec
  // wouldn't trigger surface mutation anyway).
  return Object.freeze(cfg) as ResolvedSpec;
}
