// WARNING: do not edit this file directly, it is generated dynamically from
// the source JSDOC comments using the npm run docs script.

import React from "react";
import {argTypes as axisArgTypes} from "./Axis.args.jsx";
import {assign} from "@d3plus/dom";

import {AxisTop as D3plusAxisTop} from "@d3plus/react";
export const AxisTop = ({ config }) => <D3plusAxisTop config={config} />;

export const argTypes = assign(

  /**
   * Filters out unused argTypes from the Axis primitive and
   * overrides any defaults that have been changed in AxisTop
   */
  Object.keys(axisArgTypes)
    .reduce((obj, k) => (obj[k] = axisArgTypes[k], obj), {}),

  /**
   * AxisTop-specific methods
   */
  
  {
    orient: {
      control: {
        type: "text"
      },
      defaultValue: "top",
      description: "Supports `\"top\"`, `\"right\"`, `\"bottom\"`, and `\"left\"` orientations.",
      table: {
        defaultValue: {
          summary: "top"
        }
      },
      type: {
        required: false,
        summary: "string"
      }
    }
  }
);
