// WARNING: do not edit this file directly, it is generated dynamically from
// the source JSDOC comments using the npm run docs script.

import React from "react";
import {argTypes as axisArgTypes} from "./Axis.args.jsx";
import {assign} from "@d3plus/dom";

import {AxisTop as D3plusAxisTop} from "@d3plus/react";
export const AxisTop = ({ config }) => <D3plusAxisTop config={config} />;

export const argTypes = assign(

  /**
   * Filters out unused argTypes from the Axis primitive and
   * overrides any defaults that have been changed in AxisTop
   */
  Object.keys(axisArgTypes)
    .reduce((obj, k) => (obj[k] = axisArgTypes[k], obj), {}),

  /**
   * AxisTop-specific methods
   */
  
  {
    barConfig: {
      control: {},
      description: "Axis line style.",
      table: {
        defaultValue: {
          summary: "undefined"
        }
      },
      type: {
        required: true,
        summary: "record"
      }
    },
    config: {
      control: {},
      description: "Methods that correspond to the key/value pairs and returns this class.",
      table: {
        defaultValue: {
          summary: "undefined"
        }
      },
      type: {
        required: true,
        summary: "d3plusconfig"
      }
    },
    data: {
      control: {},
      description: "An array of data points, which helps determine which ticks should be shown and which time resolution should be displayed.",
      table: {
        defaultValue: {
          summary: "undefined"
        }
      },
      type: {
        required: true,
        summary: "array.&lt;any&gt;"
      }
    },
    gridConfig: {
      control: {},
      description: "Grid config of the axis.",
      table: {
        defaultValue: {
          summary: "undefined"
        }
      },
      type: {
        required: true,
        summary: "record"
      }
    },
    labelRotation: {
      control: {
        type: "boolean"
      },
      description: "Whether to rotate horizontal axis labels -90 degrees.",
      table: {
        defaultValue: {
          summary: "undefined"
        }
      },
      type: {
        required: true,
        summary: "boolean"
      }
    },
    locale: {
      control: {
        type: "object"
      },
      description: "The locale used for all text and number formatting. Supports the locales defined in [d3plus-format](https://github.com/d3plus/d3plus-format/blob/master/src/locale.js). The locale can be a complex Object, a locale code (like \"en-US\"), or a 2-digit language code (like \"en\"). If a 2-digit code is provided, the \"findLocale\" function is used to identify the most approximate locale.",
      table: {
        defaultValue: {
          summary: "undefined"
        }
      },
      type: {
        required: true,
        summary: "string | object"
      }
    },
    on: {
      control: {
        type: "text"
      },
      description: "Event listener for the specified event *typenames*. Mirrors the core [d3-selection](https://github.com/d3/d3-selection#selection_on) behavior.",
      table: {
        defaultValue: {
          summary: "undefined"
        }
      },
      type: {
        required: true,
        summary: "string"
      }
    },
    orient: {
      control: {
        type: "text"
      },
      defaultValue: "top",
      description: "The orientation of the shape.",
      table: {
        defaultValue: {
          summary: "top"
        }
      },
      type: {
        required: true,
        summary: "string"
      }
    },
    parent: {
      control: {},
      description: "Parent config used by the wrapper.",
      table: {
        defaultValue: {
          summary: "undefined"
        }
      },
      type: {
        required: true,
        summary: "unknown"
      }
    },
    render: {
      control: {},
      description: "Renders the current Axis to the page.",
      table: {
        defaultValue: {
          summary: "undefined"
        }
      },
      type: {
        required: false,
        summary: "function"
      }
    },
    select: {
      control: {
        type: "text"
      },
      description: "The SVG container element as a d3 selector or DOM element.\n\nPassing `null` or `undefined` deliberately leaves the axis unmounted\n— `renderMode(\"compute\")` plus `select(null)` produces a\nscene-only axis (no detached SVG fallback). This is the formal\ncontract callers in `plotPaint` use to compute axis layout without\nmounting DOM.",
      table: {
        defaultValue: {
          summary: "undefined"
        }
      },
      type: {
        required: true,
        summary: "string | htmlelement | null | undefined"
      }
    },
    shapeConfig: {
      control: {},
      description: "Configuration object with key/value pairs applied as method calls on each shape.",
      table: {
        defaultValue: {
          summary: "undefined"
        }
      },
      type: {
        required: true,
        summary: "d3plusconfig"
      }
    },
    titleConfig: {
      control: {},
      description: "Title configuration of the axis.",
      table: {
        defaultValue: {
          summary: "undefined"
        }
      },
      type: {
        required: true,
        summary: "record"
      }
    },
    translate: {
      control: {},
      description: "Defines how informational text strings should be displayed. By default, this function will try to find the string in question (which is the first argument provided to this function) inside of an internally managed translation Object. If you'd like to override to use custom text, simply pass this method your own custom formatting function.",
      table: {
        defaultValue: {
          summary: "undefined"
        }
      },
      type: {
        required: true,
        summary: "function"
      }
    }
  }
);
