// WARNING: do not edit this file directly, it is generated dynamically from
// the source JSDOC comments using the npm run docs script.

import React from "react";
import {argTypes as baseClassArgTypes} from "../utils/BaseClass.args.jsx";
import {assign} from "@d3plus/dom";

import {SizeLegend as D3plusSizeLegend} from "@d3plus/react";
export const SizeLegend = ({ config }) => <D3plusSizeLegend config={config} />;

export const argTypes = assign(

  /**
   * Filters out unused argTypes from the BaseClass primitive and
   * overrides any defaults that have been changed in SizeLegend
   */
  Object.keys(baseClassArgTypes)
    .reduce((obj, k) => (obj[k] = baseClassArgTypes[k], obj), {}),

  /**
   * SizeLegend-specific methods
   */
  
  {
    colorDefaults: {
      control: {},
      description: "Overrides the default colors used when assigning fills from data and choosing legible text colors: `dark` and `light` (the text colors picked for contrast against a background), `missing` (null/undefined values), `on`/`off` (`true`/`false` values), `sequential` (the anchor hue for magnitude ramps), and `scale` (the categorical palette, given as a d3 ordinal scale or an array of colors). Keys are merged into the current defaults, and a Viz passes its overrides down to the shapes and components it draws.",
      table: {
        defaultValue: {
          summary: "undefined"
        }
      },
      type: {
        required: true,
        summary: "colordefaultsconfig"
      }
    },
    config: {
      control: {},
      description: "Methods that correspond to the key/value pairs and returns this class.",
      table: {
        defaultValue: {
          summary: "undefined"
        }
      },
      type: {
        required: true,
        summary: "d3plusconfig"
      }
    },
    labelConfig: {
      control: {},
      description: "Font settings for the value labels: `fontColor`, `fontFamily`, `fontSize`. Merged into the current settings.",
      table: {
        defaultValue: {
          summary: "undefined"
        }
      },
      type: {
        required: true,
        summary: "sizelegendtextconfig"
      }
    },
    labelPadding: {
      control: {
        type: "number"
      },
      defaultValue: 4,
      description: "Gap between each leader line and its label, in pixels.",
      table: {
        defaultValue: {
          summary: "4"
        }
      },
      type: {
        required: false,
        summary: "number"
      }
    },
    lineConfig: {
      control: {},
      description: "Paint for the leader lines: `stroke`, `strokeWidth`, `strokeOpacity`, `strokeDasharray`. Merged into the current settings.",
      table: {
        defaultValue: {
          summary: "undefined"
        }
      },
      type: {
        required: true,
        summary: "sizelegendlineconfig"
      }
    },
    lineLength: {
      control: {
        type: "number"
      },
      defaultValue: 6,
      description: "Length of the leader lines past the largest circle, in pixels.",
      table: {
        defaultValue: {
          summary: "6"
        }
      },
      type: {
        required: false,
        summary: "number"
      }
    },
    locale: {
      control: {
        type: "object"
      },
      description: "The locale used for all text and number formatting. Supports the locales defined in [d3plus-format](https://github.com/d3plus/d3plus-format/blob/master/src/locale.js). The locale can be a complex Object, a locale code (like \"en-US\"), or a 2-digit language code (like \"en\"). If a 2-digit code is provided, the \"findLocale\" function is used to identify the most approximate locale.",
      table: {
        defaultValue: {
          summary: "undefined"
        }
      },
      type: {
        required: true,
        summary: "string | object"
      }
    },
    on: {
      control: {
        type: "text"
      },
      description: "Event listener for the specified event *typenames*. Mirrors the core [d3-selection](https://github.com/d3/d3-selection#selection_on) behavior.",
      table: {
        defaultValue: {
          summary: "undefined"
        }
      },
      type: {
        required: true,
        summary: "string"
      }
    },
    padding: {
      control: {
        type: "number"
      },
      defaultValue: 4,
      description: "",
      table: {
        defaultValue: {
          summary: "4"
        }
      },
      type: {
        required: false,
        summary: "number"
      }
    },
    parent: {
      control: {},
      description: "Parent config used by the wrapper.",
      table: {
        defaultValue: {
          summary: "undefined"
        }
      },
      type: {
        required: true,
        summary: "unknown"
      }
    },
    render: {
      control: {},
      description: "Renders the legend. Standalone, it paints into the `select` container\n(sized to the legend); inside a chart (`renderMode(\"compute\")`) it only\nlays out, and the chart composes `toScene()`.",
      table: {
        defaultValue: {
          summary: "undefined"
        }
      },
      type: {
        required: false,
        summary: "function"
      }
    },
    scale: {
      control: {},
      description: "Scale factor (1 = identity).",
      table: {
        defaultValue: {
          summary: "undefined"
        }
      },
      type: {
        required: false,
        summary: "constoraccessor"
      }
    },
    select: {
      control: {
        type: "text"
      },
      description: "The container element for a standalone render, as a d3 selector or DOM element.",
      table: {
        defaultValue: {
          summary: "undefined"
        }
      },
      type: {
        required: true,
        summary: "string | htmlelement | svgelement"
      }
    },
    shapeConfig: {
      control: {},
      description: "Paint for the circles: `fill`, `fillOpacity`, `stroke`, `strokeWidth`, `strokeOpacity`. Merged into the current settings.",
      table: {
        defaultValue: {
          summary: "undefined"
        }
      },
      type: {
        required: true,
        summary: "sizelegendshapeconfig"
      }
    },
    tickFormat: {
      control: {},
      description: "Formats each value's label. Defaults to the locale's abbreviated number format.",
      table: {
        defaultValue: {
          summary: "undefined"
        }
      },
      type: {
        required: false,
        summary: "function"
      }
    },
    title: {
      control: {
        type: "text"
      },
      description: "Title above the circles. Defaults to the `size` key when `size` is set to a string.",
      table: {
        defaultValue: {
          summary: "undefined"
        }
      },
      type: {
        required: false,
        summary: "string"
      }
    },
    titleConfig: {
      control: {},
      description: "Font settings for the title: `fontColor`, `fontFamily`, `fontSize`, `fontWeight`. Merged into the current settings.",
      table: {
        defaultValue: {
          summary: "undefined"
        }
      },
      type: {
        required: true,
        summary: "sizelegendtextconfig"
      }
    },
    toScene: {
      control: {
        type: "number"
      },
      defaultValue: "0",
      description: "Produces a backend-agnostic scene graph of the last layout, offset by the\noptional transform.",
      table: {
        defaultValue: {
          summary: "0"
        }
      },
      type: {
        required: false,
        summary: "number"
      }
    },
    translate: {
      control: {},
      description: "Defines how informational text strings should be displayed. By default, this function will try to find the string in question (which is the first argument provided to this function) inside of an internally managed translation Object. If you'd like to override to use custom text, simply pass this method your own custom formatting function.",
      table: {
        defaultValue: {
          summary: "undefined"
        }
      },
      type: {
        required: true,
        summary: "function"
      }
    },
    values: {
      control: {
        type: "object"
      },
      description: "The values to draw circles for: an array of values, how many to pick\nfrom the size domain (default 3: its min, max, and a round middle), or\na function receiving the `[min, max]` domain and returning values.",
      table: {
        defaultValue: {
          summary: "undefined"
        }
      },
      type: {
        required: false,
        summary: "number | array.&lt;number&gt; | function"
      }
    }
  }
);
