// WARNING: do not edit this file directly, it is generated dynamically from
// the source JSDOC comments using the npm run docs script.

import React from "react";
import {argTypes as plotArgTypes} from "./Plot.args.jsx";
import {assign} from "@d3plus/dom";

import {AreaPlot as D3plusAreaPlot} from "@d3plus/react";
export const AreaPlot = ({ config }) => <D3plusAreaPlot config={config} />;

export const argTypes = assign(

  /**
   * Filters out unused argTypes from the Plot primitive and
   * overrides any defaults that have been changed in AreaPlot
   */
  Object.keys(plotArgTypes)
    .filter(k => !k.match(/^(shape|zoom.*)$/))
    .reduce((obj, k) => (obj[k] = plotArgTypes[k], obj), {}),

  /**
   * AreaPlot-specific methods
   */
  
  {
    baseline: {
      control: {
        type: "number"
      },
      defaultValue: 0,
      description: "Sets the baseline for the x/y plot. If *value* is not specified, returns the current baseline.",
      table: {
        defaultValue: {
          summary: 0
        }
      },
      type: {
        required: true,
        summary: "number"
      }
    },
    discrete: {
      control: {
        type: "text"
      },
      defaultValue: "x",
      description: "If *value* is specified, sets the discrete accessor to the specified method name (usually an axis) and returns the current class instance.",
      table: {
        defaultValue: {
          summary: "x"
        }
      },
      type: {
        required: false,
        summary: "string"
      }
    },
    shape: {
      control: {
        type: "text"
      },
      defaultValue: "Area",
      description: "Changes the primary shape used to represent each data point in a visualization. Not all visualizations support changing shapes, this method can be provided the String name of a D3plus shape class (for example, \"Rect\" or \"Circle\"), or an accessor Function that returns the String class name to be used for each individual data point.",
      table: {
        defaultValue: {
          summary: "Area"
        }
      },
      type: {
        required: false,
        summary: "string | function"
      }
    }
  }
);
