// WARNING: do not edit this file directly, it is generated dynamically from
// the source JSDOC comments using the npm run docs script.

import React from "react";
import {argTypes as pieArgTypes} from "./Pie.args.jsx";
import {assign} from "@d3plus/dom";

import {Donut as D3plusDonut} from "@d3plus/react";
export const Donut = ({ config }) => <D3plusDonut config={config} />;

export const argTypes = assign(

  /**
   * Filters out unused argTypes from the Pie primitive and
   * overrides any defaults that have been changed in Donut
   */
  Object.keys(pieArgTypes)
    .filter(k => !k.match(/^(shape)$/))
    .reduce((obj, k) => (obj[k] = pieArgTypes[k], obj), {}),

  /**
   * Donut-specific methods
   */
  
  {
    innerRadius: {
      table: {
        defaultValue: {
          summary: "function"
        }
      }
    },
    padPixel: {
      defaultValue: 2,
      table: {
        defaultValue: {
          summary: "2"
        }
      }
    }
  }
);
