// WARNING: do not edit this file directly, it is generated dynamically from
// the source JSDOC comments using the npm run docs script.

import React from "react";
import {argTypes as vizArgTypes} from "./Viz.args.jsx";
import {assign} from "@d3plus/dom";

import {Gauge as D3plusGauge} from "@d3plus/react";
export const Gauge = ({ config }) => <D3plusGauge config={config} />;

export const argTypes = assign(

  /**
   * Filters out unused argTypes from the Viz primitive.
   */
  Object.keys(vizArgTypes)
    .filter(k => !k.match(/^(zoom.*)$/))
    .reduce((obj, k) => (obj[k] = vizArgTypes[k], obj), {}),

  /**
   * Gauge-specific methods
   */
  {
    axisConfig: {
      control: {},
      description: "Styles the dial: `shapeConfig.fill` colors the track, `shapeConfig.stroke`/`strokeWidth` the tick marks, and `shapeConfig.labelConfig` (`fontColor`, `fontFamily`, `fontSize`) the tick, value, and name labels. Unset colors follow the chart's background, so the dial reads on light and dark themes alike.",
      table: {
        defaultValue: {
          summary: "undefined"
        }
      },
      type: {
        required: false,
        summary: "{shapeConfig: {fill, stroke, strokeWidth, labelConfig}}"
      }
    },
    bands: {
      control: {},
      description: "Colored zones along the dial, in order: `[{max: 60, color: \"#2f9e44\"}, {max: 85, color: \"#f59f00\"}, {color: \"#e03131\"}]`. Each band starts at its own `min`, else where the previous band ended; it ends at its own `max`, else the domain's maximum. Bands are drawn on the track behind the needles, or as a thin strip inside the progress tracks.",
      table: {
        defaultValue: {
          summary: "[]"
        }
      },
      type: {
        required: false,
        summary: "GaugeBand[]"
      }
    },
    domain: {
      control: {},
      description: "The `[min, max]` the dial spans. Either end may be left `undefined` to come from the data (and any band edges), rounded outward to nice numbers and always including zero. Values outside the domain pin the indicator to the nearest end.",
      table: {
        defaultValue: {
          summary: "undefined"
        }
      },
      type: {
        required: false,
        summary: "[number, number]"
      }
    },
    endAngle: {
      control: {
        type: "number"
      },
      description: "The angle, in degrees clockwise from 12 o'clock, where the dial ends.",
      table: {
        defaultValue: {
          summary: "120"
        }
      },
      type: {
        required: false,
        summary: "number"
      }
    },
    indicator: {
      control: {
        type: "radio"
      },
      options: ["needle", "progress"],
      description: "How each row shows its value: `\"needle\"` (default) points a needle at it; `\"progress\"` fills a track from the minimum up to it, with one concentric track per row stepping inward.",
      table: {
        defaultValue: {
          summary: "\"needle\""
        }
      },
      type: {
        required: false,
        summary: "\"needle\" | \"progress\""
      }
    },
    minorTicks: {
      control: {
        type: "boolean"
      },
      description: "Whether to draw unlabeled minor ticks between the major ticks.",
      table: {
        defaultValue: {
          summary: "true"
        }
      },
      type: {
        required: false,
        summary: "boolean"
      }
    },
    startAngle: {
      control: {
        type: "number"
      },
      description: "The angle, in degrees clockwise from 12 o'clock, where the dial starts.",
      table: {
        defaultValue: {
          summary: "-120"
        }
      },
      type: {
        required: false,
        summary: "number"
      }
    },
    thickness: {
      control: {
        type: "number"
      },
      description: "The track's thickness, as a fraction of the dial's radius.",
      table: {
        defaultValue: {
          summary: "0.2"
        }
      },
      type: {
        required: false,
        summary: "number"
      }
    },
    tickFormat: {
      control: {},
      description: "Formats the tick labels. Defaults to the locale's abbreviated number format.",
      table: {
        defaultValue: {
          summary: "formatAbbreviate"
        }
      },
      type: {
        required: false,
        summary: "function"
      }
    },
    ticks: {
      control: {},
      description: "The major ticks: a target count, an explicit array of values, or `false` for none. Counted ticks always label both ends of the domain.",
      table: {
        defaultValue: {
          summary: "undefined"
        }
      },
      type: {
        required: false,
        summary: "number | number[] | false"
      }
    },
    value: {
      control: {
        type: "text"
      },
      description: "Accessor function or string key for each row's value.",
      table: {
        defaultValue: {
          summary: "\"value\""
        }
      },
      type: {
        required: false,
        summary: "string | function"
      }
    },
    valueFormat: {
      control: {},
      description: "Formats the value shown under the hub and in each tooltip, as `(value, datum) => string`. Defaults to the locale's abbreviated number format.",
      table: {
        defaultValue: {
          summary: "formatAbbreviate"
        }
      },
      type: {
        required: false,
        summary: "function"
      }
    }
  }
);
