// WARNING: do not edit this file directly, it is generated dynamically from
// the source JSDOC comments using the npm run docs script.

import React from "react";
import {argTypes as plotArgTypes} from "./Plot.args.jsx";
import {assign} from "@d3plus/dom";

import {Histogram as D3plusHistogram} from "@d3plus/react";
export const Histogram = ({ config }) => <D3plusHistogram config={config} />;

export const argTypes = assign(

  /**
   * Filters out unused argTypes from the Plot primitive; Histogram derives
   * its bars' shape and x/y positions from the binned data.
   */
  Object.keys(plotArgTypes)
    .filter(k => !k.match(/^(shape|x|x2|y|y2|discrete|zoom.*)$/))
    .reduce((obj, k) => (obj[k] = plotArgTypes[k], obj), {}),

  /**
   * Histogram-specific methods
   */
  {
    binDomain: {
      control: {},
      description: "`[min, max]` to bin across. Defaults to the nicely rounded extent of the values.",
      table: {
        defaultValue: {
          summary: "undefined"
        }
      },
      type: {
        required: false,
        summary: "[number, number]"
      }
    },
    binNormalize: {
      control: {
        type: "radio"
      },
      options: ["count", "density", "relative"],
      description: "What each bar's height measures: `\"count\"` (default), `\"density\"` (count ÷ (total × bin width), so the bars' area sums to 1), or `\"relative\"` (count ÷ total, so the heights sum to 1).",
      table: {
        defaultValue: {
          summary: "\"count\""
        }
      },
      type: {
        required: false,
        summary: "\"count\" | \"density\" | \"relative\""
      }
    },
    binThresholds: {
      control: {},
      description: "Bin edges: a bin count, an array of interior edges, or a d3-array threshold generator such as `thresholdSturges` (the default), `thresholdScott`, or `thresholdFreedmanDiaconis`.",
      table: {
        defaultValue: {
          summary: "thresholdSturges"
        }
      },
      type: {
        required: false,
        summary: "number | number[] | function"
      }
    },
    binWidth: {
      control: {
        type: "number"
      },
      description: "A uniform bin width, with edges at multiples of the width. When set, takes precedence over `binThresholds`.",
      table: {
        defaultValue: {
          summary: "undefined"
        }
      },
      type: {
        required: false,
        summary: "number"
      }
    },
    value: {
      control: {
        type: "text"
      },
      description: "Accessor function or string key for each row's numeric observation.",
      table: {
        defaultValue: {
          summary: "\"value\""
        }
      },
      type: {
        required: false,
        summary: "string | function"
      }
    }
  }
);
