// WARNING: do not edit this file directly, it is generated dynamically from
// the source JSDOC comments using the npm run docs script.

import React from "react";
import {argTypes as vizArgTypes} from "./Viz.args.jsx";
import {assign} from "@d3plus/dom";

import {Priestley as D3plusPriestley} from "@d3plus/react";
export const Priestley = ({ config }) => <D3plusPriestley config={config} />;

export const argTypes = assign(

  /**
   * Filters out unused argTypes from the Viz primitive and
   * overrides any defaults that have been changed in Priestley
   */
  Object.keys(vizArgTypes)
    .filter(k => !k.match(/^(zoom.*)$/))
    .reduce((obj, k) => (obj[k] = vizArgTypes[k], obj), {}),

  /**
   * Priestley-specific methods
   */
  
  {
    axisConfig: {
      control: {
        type: "object"
      },
      defaultValue: "{scale: time}",
      description: "If *value* is specified, sets the config method for the axis and returns the current class instance. If *value* is not specified, returns the current axis configuration.",
      table: {
        defaultValue: {
          summary: "{scale: time}"
        }
      },
      type: {
        required: false,
        summary: "object"
      }
    },
    end: {
      control: {
        type: "text"
      },
      defaultValue: "end",
      description: "If *value* is specified, sets the end accessor to the specified function or key and returns the current class instance. If *value* is not specified, returns the current end accessor.",
      table: {
        defaultValue: {
          summary: "end"
        }
      },
      type: {
        required: false,
        summary: "function | string"
      }
    },
    paddingInner: {
      control: {
        type: "number"
      },
      defaultValue: 0.05,
      description: "Sets the [paddingInner](https://github.com/d3/d3-scale#band_paddingInner) value of the underlining [Band Scale](https://github.com/d3/d3-scale#band-scales) used to determine the height of each bar. Values should be a ratio between 0 and 1 representing the space in between each rectangle.",
      table: {
        defaultValue: {
          summary: 0.05
        }
      },
      type: {
        required: false,
        summary: "number"
      }
    },
    paddingOuter: {
      control: {
        type: "number"
      },
      defaultValue: 0.05,
      description: "Sets the [paddingOuter](https://github.com/d3/d3-scale#band_paddingOuter) value of the underlining [Band Scale](https://github.com/d3/d3-scale#band-scales) used to determine the height of each bar. Values should be a ratio between 0 and 1 representing the space around the outer rectangles.",
      table: {
        defaultValue: {
          summary: 0.05
        }
      },
      type: {
        required: false,
        summary: "number"
      }
    },
    shapeConfig: {
      control: {
        type: "object"
      },
      defaultValue: "assign({}, this._shapeConfig, {ariaLabel: (d, i) => `${this._drawLabel(d, i)}, ${this._start(d, i)} - ${this._end(d, i)}.`})",
      description: "If *value* is specified, sets the config method for each shape and returns the current class instance.",
      table: {
        defaultValue: {
          detail: "assign({}, this._shapeConfig, {ariaLabel: (d, i) => `${this._drawLabel(d, i)}, ${this._start(d, i)} - ${this._end(d, i)}.`})",
          summary: "function"
        }
      },
      type: {
        required: false,
        summary: "object"
      }
    },
    start: {
      control: {
        type: "text"
      },
      defaultValue: "start",
      description: "If *value* is specified, sets the start accessor to the specified function or key and returns the current class instance. If *value* is not specified, returns the current start accessor.",
      table: {
        defaultValue: {
          summary: "start"
        }
      },
      type: {
        required: false,
        summary: "function | string"
      }
    }
  }
);
