// WARNING: do not edit this file directly, it is generated dynamically from
// the source JSDOC comments using the npm run docs script.

import React from "react";

import {Viz as D3plusViz} from "@d3plus/react";
export const Viz = ({ config }) => <D3plusViz config={config} />;

export const argTypes = {
  active: {
    control: {},
    description: "The active callback function for highlighting shapes.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "false | function"
    }
  },
  aggs: {
    control: {},
    description: "Custom aggregation methods for each data key.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "record"
    }
  },
  ariaHidden: {
    control: {
      type: "boolean"
    },
    defaultValue: true,
    description: "Hides the SVG from assistive technology when true (`aria-hidden`).",
    table: {
      defaultValue: {
        summary: "true"
      }
    },
    type: {
      required: false,
      summary: "boolean"
    }
  },
  attribution: {
    control: {
      type: "text"
    },
    description: "Sets text to be shown positioned absolute on top of the visualization in the bottom-right corner. This is most often used in Geomaps to display the copyright of map tiles. The text is rendered as HTML, so any valid HTML string will render as expected (eg. anchor links work).",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "string | boolean"
    }
  },
  attributionIcon: {
    control: {
      type: "text"
    },
    description: "Overrides the \"ⓘ\" icon a long attribution collapses to (see `attribution`), which otherwise renders as an inline SVG. Accepts an HTML string — used as the toggle button's content — or a mount function, `(el: HTMLElement) => void | (() => void)`, called once with the button's reserved icon slot so a live component (a React tree via `createRoot(el).render(...)`, or anything else imperative) can be mounted into it. A returned cleanup function runs right before that slot is discarded, which happens whenever the credit's markup regenerates (its text or theme changes), not just once per chart.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "string | function"
    }
  },
  attributionStyle: {
    control: {},
    description: "Configuration object for the attribution style.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "record"
    }
  },
  backConfig: {
    control: {},
    description: "Configuration object for the back button. Superseded by\n`.backControlStyle()`/`.backControlClassName()` for the button's\nappearance (it renders as a real `<button>`, like the zoom/search\ncontrols, not a configurable text node) — kept for backwards\ncompatibility, but no longer affects how the button looks.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "record"
    }
  },
  backControlClassName: {
    control: {
      type: "text"
    },
    description: "An additional CSS class name (or space-separated list of class names) applied to the back button, alongside its fixed `back-control` class. Setting this automatically disables d3plus's built-in inline `backControlStyle` default (as long as you haven't already customized it yourself), so a host page's own button styling — Tailwind, Bootstrap, a design system — applies through the cascade with no other configuration needed.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "string"
    }
  },
  backControlStyle: {
    control: {},
    description: "An object containing CSS key/value pairs that is used to style the back button. Passing `false` will remove all default styling. Automatically skipped (as if `false`) once `.backControlClassName(...)` is set, unless you've explicitly customized this yourself.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "false | record"
    }
  },
  cache: {
    control: {
      type: "boolean"
    },
    defaultValue: true,
    description: "Whether to cache the processed data between renders.",
    table: {
      defaultValue: {
        summary: "true"
      }
    },
    type: {
      required: false,
      summary: "boolean"
    }
  },
  color: {
    control: {
      type: "text"
    },
    description: "Defines the main color to be used for each data point in a visualization. Can be either an accessor function or a string key to reference in each data point. If a color value is returned, it will be used as is. If a string is returned, a unique color will be assigned based on the string.\n\nWhen the color is a category that isn't one of the `groupBy` levels (for example, points grouped by `\"country\"` and colored by `\"region\"`), the legend shows one entry per category, labelled by the category. Clicking, shift+clicking, or hovering an entry hides, solos, or highlights every item in that category.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "string | false | function"
    }
  },
  colorDefaults: {
    control: {},
    description: "Overrides the default colors used when assigning fills from data and choosing legible text colors: `dark` and `light` (the text colors picked for contrast against a background), `missing` (null/undefined values), `on`/`off` (`true`/`false` values), `sequential` (the anchor hue for magnitude ramps), and `scale` (the categorical palette, given as a d3 ordinal scale or an array of colors). Keys are merged into the current defaults, and a Viz passes its overrides down to the shapes and components it draws.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: true,
      summary: "colordefaultsconfig"
    }
  },
  colorOrdinal: {
    control: {
      type: "boolean"
    },
    defaultValue: false,
    description: "Treat a discrete color field as ordered: color it with a single-hue light→dark ramp instead of nominal categorical hues.",
    table: {
      defaultValue: {
        summary: "false"
      }
    },
    type: {
      required: false,
      summary: "boolean"
    }
  },
  colorScale: {
    control: {
      type: "text"
    },
    description: "Defines the value to be used for a color scale. Can be either an accessor function or a string key to reference in each data point.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "string | false | function"
    }
  },
  colorScaleConfig: {
    control: {},
    description: "A pass-through to the config method of ColorScale.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "record"
    }
  },
  colorScaleMaxSize: {
    control: {
      type: "number"
    },
    description: "The maximum pixel size for drawing the color scale: width for horizontal scales and height for vertical scales.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "number"
    }
  },
  colorScalePadding: {
    control: {
      type: "boolean"
    },
    description: "Tells the colorScale whether or not to use the internal padding defined by the visualization in it's positioning. For example, d3plus-plot will add padding on the left so that the colorScale appears centered above the x-axis. By default, this padding is only applied on screens larger than 600 pixels wide.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "boolean | function"
    }
  },
  colorScalePosition: {
    control: {
      type: "text"
    },
    description: "Defines which side of the visualization to anchor the color scale. Acceptable values are `\"top\"`, `\"bottom\"`, `\"left\"`, `\"right\"`, and `false`. A `false` value will cause the color scale to not be displayed, but will still color shapes based on the scale.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "string | boolean | function"
    }
  },
  config: {
    control: {},
    description: "Methods that correspond to the key/value pairs and returns this class.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: true,
      summary: "d3plusconfig"
    }
  },
  data: {
    control: {
      type: "object"
    },
    description: "The primary data array used to draw the visualization. The value passed should be an *Array* of objects or a *String* representing a filepath or URL to be loaded. The following filetypes are supported: `csv`, `tsv`, `txt`, and `json`.\n\nIf your data URL needs specific headers to be set, an Object with \"url\" and \"headers\" keys may also be passed.\n\nAdditionally, a custom formatting function can be passed as a second argument to this method. This custom function will be passed the data that has been loaded, as long as there are no errors. This function should return the final array of obejcts to be used as the primary data array. For example, some JSON APIs return the headers split from the data values to save bandwidth. These would need be joined using a custom formatter.\n\nIf you would like to specify certain configuration options based on the yet-to-be-loaded data, you can also return a full `config` object from the data formatter (including the new `data` array as a key in the object).\n\nDefaults to an empty array (`[]`).",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "string | array.&lt;datapoint&gt; | object"
    }
  },
  dataCutoff: {
    control: {
      type: "number"
    },
    defaultValue: 100,
    description: "Maximum number of data points to render before downsampling.",
    table: {
      defaultValue: {
        summary: "100"
      }
    },
    type: {
      required: false,
      summary: "number"
    }
  },
  depth: {
    control: {
      type: "number"
    },
    description: "Active depth level for nested groupings.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "number"
    }
  },
  detectResize: {
    control: {
      type: "boolean"
    },
    description: "If the width and/or height of a Viz is not user-defined, it is determined by the size of it's parent element. When this method is set to `true`, the Viz will listen for the `window.onresize` event and adjust it's dimensions accordingly.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "boolean"
    }
  },
  detectResizeDelay: {
    control: {
      type: "number"
    },
    description: "When resizing the browser window, this is the millisecond delay to trigger the resize event.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "number"
    }
  },
  detectVisible: {
    control: {
      type: "boolean"
    },
    description: "Toggles whether or not the Viz should try to detect if it visible in the current viewport. When this method is set to `true`, the Viz will only be rendered when it has entered the viewport either through scrolling or if it's display or visibility is changed.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "boolean"
    }
  },
  detectVisibleInterval: {
    control: {
      type: "number"
    },
    description: "The interval, in milliseconds, for checking if the visualization is visible on the page. When `detectVisible` defers a render until the visualization scrolls into view, this is also how long it must stay in view before it renders, so visualizations scrolled past quickly are never drawn.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "number"
    }
  },
  detectVisibleUnload: {
    control: {
      type: "boolean"
    },
    description: "When `true` (the default) and `detectVisible` is enabled, the Viz releases its DOM and scene while it is scrolled out of view and redraws when it returns, keeping the page light when there are many visualizations. Data and configuration are retained; interaction state such as zoom or selection is not, so set this to `false` to keep it. With `detectVisible` enabled, each chart's `<svg>` is also given `content-visibility: auto`, so the browser skips rendering its contents while it is far off-screen (this matters most when this is `false` and charts are kept). For a larger saving you can also apply `content-visibility: auto` and a `contain-intrinsic-size` to the container element yourself; that adds paint containment to an element you own, so it is not done automatically. Requires `IntersectionObserver`.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "boolean"
    }
  },
  discrete: {
    control: {
      type: "radio"
    },
    description: "Discrete-axis key (\"x\" | \"y\") for charts that flip layout per axis.",
    options: [
      "x",
      "y"
    ],
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "\"x\" | \"y\""
    }
  },
  duration: {
    control: {
      type: "number"
    },
    defaultValue: 600,
    description: "Animation duration in ms.",
    table: {
      defaultValue: {
        summary: "600"
      }
    },
    type: {
      required: false,
      summary: "number"
    }
  },
  filter: {
    control: {},
    description: "Predicate filtering which data points are included, or false to disable.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "false | function"
    }
  },
  fontFamily: {
    control: {
      type: "text"
    },
    description: "The font family used throughout the visualization.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "string | array.&lt;string&gt;"
    }
  },
  groupBy: {
    control: {
      type: "text"
    },
    description: "Defines the mapping between data and shape. The value can be a String matching a key in each data point (default is \"id\"), or an accessor Function that returns a unique value for each data point. Additionally, an Array of these values may be provided if the visualization supports nested hierarchies.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "string | function | array.&lt;string | function&gt;"
    }
  },
  height: {
    control: {
      type: "number"
    },
    description: "Overall height of the visualization in pixels.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "number"
    }
  },
  hiddenColor: {
    control: {
      type: "text"
    },
    description: "Defines the color used for legend shapes when the corresponding grouping is hidden from display (by clicking on the legend).",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "string | function"
    }
  },
  hiddenOpacity: {
    control: {
      type: "number"
    },
    description: "Defines the opacity used for legend labels when the corresponding grouping is hidden from display (by clicking on the legend).",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "number | function"
    }
  },
  highlight: {
    control: {},
    description: "Persistently emphasizes the data points matching the given predicate: the\nmatching marks keep their color while every other mark is de-emphasized to\na neutral gray (the \"emphasis\" form — highlight one series, gray the rest).\nUnlike `hover`/`active` (transient, opacity-based), `highlight` is a\nstanding state that survives pointer movement. Pass `false` to clear it.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "false | function"
    }
  },
  hover: {
    control: {},
    description: "The hover callback function for highlighting shapes on mouseover.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "false | function"
    }
  },
  label: {
    control: {
      type: "text"
    },
    description: "Accessor function, or a constant string applied to every data point's\nlabel (unlike `value`/`nodeId`/etc., a string here is not treated as a\nper-datum object key — pass a function for that).",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "string | function"
    }
  },
  legend: {
    control: {
      type: "boolean"
    },
    description: "Whether to display the legend. By default, the legend shows when it has more than one entry and each entry stands for a single group (or two groups at most), or when the entries are colored by a category that isn't a `groupBy` level (see `color`), in which case each entry is labelled by its category. Pass `false` to hide it, `true` to always show it, or a `(config, data) => boolean` function to decide.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "boolean | function"
    }
  },
  legendConfig: {
    control: {},
    description: "Configuration object passed to the legend's config method.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "record"
    }
  },
  legendFilterInvert: {
    control: {
      type: "boolean"
    },
    description: "Defines the click functionality of categorical legend squares. When set to false, clicking will hide that category and shift+clicking will solo that category. When set to true, clicking with solo that category and shift+clicking will hide that category.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "boolean | function"
    }
  },
  legendInset: {
    control: {
      type: "boolean"
    },
    description: "Whether the chart may draw one of its legends inside the empty space around its marks instead of in a margin, for charts that leave room (Plot, Network, Pack, Pie, Rings, Tree, and Geomap). After the chart lays out, the size legend is tried first, then the legend, then the colorScale; the first that fits is drawn over a semi-transparent box (see `legendInsetConfig`), and any others keep their margins. Space enclosed by the marks, like the middle of a ring of points, is never used. A legend or colorScale whose position was set explicitly stays in that margin. Defaults to `true`; also accepts a function that receives the resolved chart config and returns a boolean.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "boolean | function"
    }
  },
  legendInsetConfig: {
    control: {},
    description: "Style of the box drawn behind a legend placed inside the chart (see `legendInset`): `fill` (defaults to the chart's background color), `fillOpacity` (0.85), `stroke` (defaults to a faint contrasting line), `strokeWidth` (1), `rx` (corner radius, 4), `margin` (space between the box's edge and the legend, 6), and `padding` (space kept between the box and the chart's marks and edges, 10).",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "record"
    }
  },
  legendPadding: {
    control: {
      type: "boolean"
    },
    description: "Tells the legend whether or not to use the internal padding defined by the visualization in it's positioning. For example, d3plus-plot will add padding on the left so that the legend appears centered underneath the x-axis. By default, this padding is only applied on screens larger than 600 pixels wide.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "boolean | function"
    }
  },
  legendPosition: {
    control: {
      type: "text"
    },
    description: "Defines which side of the visualization to anchor the legend. Expected values are `\"top\"`, `\"bottom\"`, `\"left\"`, and `\"right\"`.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "string | function"
    }
  },
  legendSort: {
    control: {},
    description: "Custom sort comparator for legend items.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "function"
    }
  },
  legendTooltip: {
    control: {},
    description: "Configuration object for the legend tooltip.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "record"
    }
  },
  link: {
    control: {},
    description: "Links this chart to every other chart with the same group name, so hovering, `active`, `highlight` (including search), and legend hide/solo clicks in one are mirrored in the rest, and a value gets the same categorical color in every chart. Rows match across charts by the value of `by` (a data key or accessor), which defaults to the chart's own id. A string is shorthand for `{group}`; set `hover`, `active`, `highlight`, `legend`, or `color` to `false` to stop sharing that behavior.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "linkoption"
    }
  },
  loadingHTML: {
    control: {
      type: "text"
    },
    description: "The inner HTML of the status message displayed when loading AJAX requests and displaying errors. Must be a valid HTML string or a function that, when passed this Viz instance, returns a valid HTML string.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "string | function"
    }
  },
  loadingMessage: {
    control: {
      type: "boolean"
    },
    description: "Toggles the visibility of the status message that is displayed when loading AJAX requests and displaying errors.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "boolean"
    }
  },
  locale: {
    control: {
      type: "object"
    },
    description: "The locale used for all text and number formatting. Supports the locales defined in [d3plus-format](https://github.com/d3plus/d3plus-format/blob/master/src/locale.js). The locale can be a complex Object, a locale code (like \"en-US\"), or a 2-digit language code (like \"en\"). If a 2-digit code is provided, the \"findLocale\" function is used to identify the most approximate locale.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: true,
      summary: "string | object"
    }
  },
  messageMask: {
    control: {
      type: "text"
    },
    description: "The color of the mask displayed underneath the status message when loading AJAX requests and displaying errors. Set to `false` to turn off the mask completely.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "string | boolean"
    }
  },
  messageStyle: {
    control: {},
    description: "Defines the CSS style properties for the status message that is displayed when loading AJAX requests and displaying errors.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "record"
    }
  },
  minimap: {
    control: {
      type: "boolean"
    },
    defaultValue: true,
    description: "Shows a small overview + draggable-viewport minimap underneath the zoom controls once the chart is zoomed in. On by default whenever `zoom` is enabled.",
    table: {
      defaultValue: {
        summary: "true"
      }
    },
    type: {
      required: false,
      summary: "boolean"
    }
  },
  minimapClassName: {
    control: {
      type: "text"
    },
    description: "An additional CSS class name (or space-separated list of class names) applied to the minimap's outer box, viewport box, and zoom-level label, alongside their fixed `d3plus-minimap` / `d3plus-minimap-viewport` / `d3plus-minimap-label` classes. Setting this automatically disables d3plus's built-in inline `minimapStyle`/`minimapViewportStyle`/`minimapViewportStyleActive`/`minimapLabelStyle` defaults (as long as you haven't already customized them yourself), so a host page's own styling applies through the cascade with no other configuration needed.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "string"
    }
  },
  minimapLabelStyle: {
    control: {},
    description: "An object containing CSS key/value pairs that is used to style the minimap's zoom-level text label (e.g. \"2x\"). Passing `false` will remove all default styling. Automatically skipped (as if `false`) once `.minimapClassName(...)` is set, unless you've explicitly customized this yourself.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "false | record"
    }
  },
  minimapStyle: {
    control: {},
    description: "An object containing CSS key/value pairs that is used to style the minimap's outer box (the full-scene overview). Passing `false` will remove all default styling. Automatically skipped (as if `false`) once `.minimapClassName(...)` is set, unless you've explicitly customized this yourself.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "false | record"
    }
  },
  minimapViewportStyle: {
    control: {},
    description: "An object containing CSS key/value pairs that is used to style the minimap's draggable viewport box in its resting state. Passing `false` will remove all default styling. Automatically skipped (as if `false`) once `.minimapClassName(...)` is set, unless you've explicitly customized this yourself.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "false | record"
    }
  },
  minimapViewportStyleActive: {
    control: {},
    description: "An object containing CSS key/value pairs that is used to style the minimap's draggable viewport box while it's being dragged. Passing `false` will remove all default styling. Automatically skipped (as if `false`) once `.minimapClassName(...)` is set, unless you've explicitly customized this yourself.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "false | record"
    }
  },
  noDataHTML: {
    control: {
      type: "text"
    },
    description: "The inner HTML of the status message displayed when no data is supplied to the visualization. Must be a valid HTML string or a function that, when passed this Viz instance, returns a valid HTML string.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "string | function"
    }
  },
  noDataMessage: {
    control: {
      type: "boolean"
    },
    description: "Toggles the visibility of the status message that is displayed when no data is supplied to the visualization.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "boolean"
    }
  },
  on: {
    control: {
      type: "text"
    },
    description: "Event listener for the specified event *typenames*. Mirrors the core [d3-selection](https://github.com/d3/d3-selection#selection_on) behavior.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: true,
      summary: "string"
    }
  },
  parent: {
    control: {},
    description: "Parent config used by the wrapper.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: true,
      summary: "unknown"
    }
  },
  render: {
    control: {},
    description: "Draws the visualization given the specified configuration.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "function"
    }
  },
  renderMode: {
    control: {
      type: "radio"
    },
    description: "\"full\" runs the DOM enter/update/exit for every shape; \"compute\"\nskips DOM work and only populates the scene data (`_textData`,\n`_shapes[i]._select`, etc.) for `toScene()` to read. Set automatically by\n`renderScene` callers; users can also opt-in.",
    options: [
      "full",
      "compute"
    ],
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: true,
      summary: "\"full\" | \"compute\""
    }
  },
  renderScene: {
    control: {},
    description: "Public entry point that renders this chart through the @d3plus/render\npluggable backends. The compute pass happens via render() (in an svg\nauto-created inside the target div); SvgRenderer/CanvasRenderer paints\nthe scene to the target. Returns `{renderer, scene}` so callers can\ninteract with the renderer (e.g. for picking) or read the scene data.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: true,
      summary: "element"
    }
  },
  renderer: {
    control: {
      type: "radio"
    },
    description: "Selects which @d3plus/render backend paints the visible output.\n`\"svg\"` = SvgRenderer (default), `\"canvas\"` = CanvasRenderer.\nBoolean arguments both normalize to `\"svg\"`.",
    options: [
      "svg",
      "canvas"
    ],
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: true,
      summary: "boolean | \"svg\" | \"canvas\""
    }
  },
  scrollContainer: {
    control: {
      type: "text"
    },
    description: "If using scroll or visibility detection, this method allow a custom override of the element to which the scroll detection function gets attached.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "string | htmlelement | window"
    }
  },
  search: {
    control: {
      type: "boolean"
    },
    defaultValue: true,
    description: "Shows a top-left search button that expands into an input; typing highlights shapes whose label matches. On by default for every chart.",
    table: {
      defaultValue: {
        summary: "true"
      }
    },
    type: {
      required: false,
      summary: "boolean"
    }
  },
  searchAccessor: {
    control: {},
    description: "Resolves the string the search box matches its typed term against, for\na given datum. Defaults to the mark's resolved on-screen label\n(`viz._drawLabel`) — the same text the user reads on the chart.\nOverride it to match against something else instead, e.g. a data\nfield that isn't shown as the label.\n\nThis is checked alongside, not instead of, every level of the datum's\nown groupBy hierarchy — searching a leaf's label also matches its\nancestor group's cell/legend entry, and vice versa, regardless of\nthis accessor's override.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "function"
    }
  },
  searchControlClassName: {
    control: {
      type: "text"
    },
    description: "An additional CSS class name (or space-separated list of class names) applied to the search toggle button and input, alongside their fixed `search-control` classes. Setting this automatically disables d3plus's built-in inline `searchControlStyle`/`searchControlStyleActive`/`searchControlStyleHover` defaults (as long as you haven't already customized them yourself), so a host page's own button styling — Tailwind, Bootstrap, a design system — applies through the cascade with no other configuration needed.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "string"
    }
  },
  searchControlStyle: {
    control: {},
    description: "An object containing CSS key/value pairs that is used to style the search toggle button. Passing `false` will remove all default styling. Automatically skipped (as if `false`) once `.searchControlClassName(...)` is set, unless you've explicitly customized this yourself.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "false | record"
    }
  },
  searchControlStyleActive: {
    control: {},
    description: "An object containing CSS key/value pairs that is used to style the search toggle button while open. Passing `false` will remove all default styling. Automatically skipped (as if `false`) once `.searchControlClassName(...)` is set, unless you've explicitly customized this yourself.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "false | record"
    }
  },
  searchControlStyleHover: {
    control: {},
    description: "An object containing CSS key/value pairs that is used to style the search toggle button on hover. Passing `false` will remove all default styling. Automatically skipped (as if `false`) once `.searchControlClassName(...)` is set, unless you've explicitly customized this yourself.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "false | record"
    }
  },
  select: {
    control: {
      type: "text"
    },
    description: "The SVG container element as a d3 selector or DOM element. Defaults to `undefined`.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "string | htmlelement"
    }
  },
  shape: {
    control: {
      type: "text"
    },
    description: "Changes the primary shape used to represent each data point in a visualization. Not all visualizations support changing shapes, this method can be provided the String name of a D3plus shape class (for example, \"Rect\" or \"Circle\"), or an accessor Function that returns the String class name to be used for each individual data point.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "string | function"
    }
  },
  shapeConfig: {
    control: {},
    description: "Configuration object with key/value pairs applied as method calls on each shape.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: true,
      summary: "d3plusconfig"
    }
  },
  sizeLegend: {
    control: {
      type: "boolean"
    },
    description: "Whether to display the size legend: a nested-circle key, in the chart's bottom-right corner, for charts that size their marks with a `size` accessor (bubble plots, Geomap points via `pointSize`, Network, Rings). By default it shows whenever marks are sized by more than one value, unless it would take up more than a third of the chart's width or height. Pass `true` to always show it, `false` to hide it, or a function that receives the resolved chart config, the radius scale, and the legend's measured `{width, height, availableWidth, availableHeight}`, and returns a boolean.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "boolean | function"
    }
  },
  sizeLegendConfig: {
    control: {},
    description: "Configuration object passed to the size legend's config method: `values` (an array of values to draw, or how many to pick), `tickFormat`, `title` (defaults to the `size` key when `size` is set to a string), `shapeConfig`, `lineConfig`, `labelConfig`, `titleConfig`, `padding`, `lineLength`, and `labelPadding`.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "record"
    }
  },
  sizeLegendPosition: {
    control: {
      type: "radio"
    },
    description: "Which margin the size legend claims in the chart's bottom-right corner. `\"right\"` (the default) widens the right margin, so the chart keeps its full height and the legend sits at the bottom of the right column, below any right-side legend or colorScale. `\"bottom\"` deepens the bottom margin instead, so the chart keeps its full width and any bottom legend or colorScale narrows to sit beside it.",
    options: [
      "right",
      "bottom"
    ],
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "\"right\" | \"bottom\""
    }
  },
  subtitle: {
    control: {
      type: "text"
    },
    description: "Accessor function or string for the visualization's subtitle.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "string | function"
    }
  },
  subtitleConfig: {
    control: {},
    description: "Configuration object for the subtitle.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "record"
    }
  },
  subtitlePadding: {
    control: {
      type: "boolean"
    },
    description: "Tells the subtitle whether or not to use the internal padding defined by the visualization in it's positioning. For example, d3plus-plot will add padding on the left so that the subtitle appears centered above the x-axis. By default, this padding is only applied on screens larger than 600 pixels wide.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "boolean | function"
    }
  },
  svgDesc: {
    control: {
      type: "text"
    },
    defaultValue: "",
    description: "Accessible description applied to the root SVG (`<desc>`).",
    table: {
      defaultValue: {
        summary: ""
      }
    },
    type: {
      required: false,
      summary: "string"
    }
  },
  svgTitle: {
    control: {
      type: "text"
    },
    defaultValue: "",
    description: "Accessible title applied to the root SVG (`<title>`).",
    table: {
      defaultValue: {
        summary: ""
      }
    },
    type: {
      required: false,
      summary: "string"
    }
  },
  tableView: {
    control: {
      type: "boolean"
    },
    defaultValue: true,
    description: "Enables the top-left table-view toggle button, which swaps the chart for a static, scrollable `<table>` of its data. On by default for every chart.",
    table: {
      defaultValue: {
        summary: "true"
      }
    },
    type: {
      required: false,
      summary: "boolean"
    }
  },
  tableViewClassName: {
    control: {
      type: "text"
    },
    description: "An additional CSS class name (or space-separated list of class names) applied to the `<table>` element the table-view toggle renders, alongside the fixed `d3plus-table-view-table` class. Lets a host page style the data table with its own table styling (Tailwind, Bootstrap, a design system) via descendant selectors.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "string"
    }
  },
  tableViewControlClassName: {
    control: {
      type: "text"
    },
    description: "An additional CSS class name (or space-separated list of class names) applied to the table-view toggle button, alongside the fixed `table-view-control`/`table-view-toggle` classes. Setting this automatically disables d3plus's built-in inline `tableViewControlStyle`/`tableViewControlStyleActive`/`tableViewControlStyleHover` defaults (as long as you haven't already customized them yourself), so a host page's own button styling applies through the cascade with no other configuration needed.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "string"
    }
  },
  tableViewControlStyle: {
    control: {},
    description: "An object containing CSS key/value pairs that is used to style the table-view toggle button. Passing `false` will remove all default styling. Automatically skipped (as if `false`) once `.tableViewControlClassName(...)` is set, unless you've explicitly customized this yourself.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "false | record"
    }
  },
  tableViewControlStyleActive: {
    control: {},
    description: "An object containing CSS key/value pairs that is used to style the table-view toggle button while it is active (showing the data table). Passing `false` will remove all default styling. Automatically skipped (as if `false`) once `.tableViewControlClassName(...)` is set, unless you've explicitly customized this yourself.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "false | record"
    }
  },
  tableViewControlStyleHover: {
    control: {},
    description: "An object containing CSS key/value pairs that is used to style the table-view toggle button on hover. Passing `false` will remove all default styling. Automatically skipped (as if `false`) once `.tableViewControlClassName(...)` is set, unless you've explicitly customized this yourself.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "false | record"
    }
  },
  tableViewDownload: {
    control: {
      type: "boolean"
    },
    defaultValue: true,
    description: "Whether the data table shows a \"download CSV\" button, exporting its full (sorted, unpaginated) rows. On by default.",
    table: {
      defaultValue: {
        summary: "true"
      }
    },
    type: {
      required: false,
      summary: "boolean"
    }
  },
  tableViewPageSize: {
    control: {
      type: "number"
    },
    description: "The number of data-table rows shown per page while in table view. Set to `false` (or any non-positive number) to disable pagination and show every row on one page.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "number | false"
    }
  },
  tableViewSort: {
    control: {
      type: "boolean"
    },
    defaultValue: true,
    description: "Whether the data table's column headers are clickable to sort (toggling asc/desc). On by default.",
    table: {
      defaultValue: {
        summary: "true"
      }
    },
    type: {
      required: false,
      summary: "boolean"
    }
  },
  threshold: {
    control: {
      type: "number"
    },
    description: "The threshold value for bucketing small data points together.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "number | function"
    }
  },
  thresholdKey: {
    control: {
      type: "text"
    },
    description: "Accessor for the value used in the threshold algorithm.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "string | function"
    }
  },
  thresholdName: {
    control: {
      type: "text"
    },
    description: "The label displayed for bucketed threshold items.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "string | function"
    }
  },
  time: {
    control: {
      type: "text"
    },
    description: "Accessor function or string key for the time dimension of each data point.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "string | false | function"
    }
  },
  timeFilter: {
    control: {},
    description: "Predicate filtering which time slices are shown, or false to disable.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "false | function"
    }
  },
  timeline: {
    control: {
      type: "boolean"
    },
    defaultValue: true,
    description: "Whether to show the timeline component.",
    table: {
      defaultValue: {
        summary: "true"
      }
    },
    type: {
      required: false,
      summary: "boolean"
    }
  },
  timelineConfig: {
    control: {},
    description: "Configuration object for the timeline.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "record"
    }
  },
  timelineDefault: {
    control: {
      type: "text"
    },
    description: "The starting time or range for the timeline. Can be a single Date/String, or an Array of 2 values representing the min and max.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "string | date | array.&lt;string | date&gt;"
    }
  },
  timelinePadding: {
    control: {
      type: "boolean"
    },
    description: "Tells the timeline whether or not to use the internal padding defined by the visualization in it's positioning. For example, d3plus-plot will add padding on the left so that the timeline appears centered underneath the x-axis. By default, this padding is only applied on screens larger than 600 pixels wide.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "boolean | function"
    }
  },
  title: {
    control: {
      type: "text"
    },
    description: "Accessor function or string for the visualization's title.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "string | function"
    }
  },
  titleConfig: {
    control: {},
    description: "Configuration object for the title.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "record"
    }
  },
  titlePadding: {
    control: {
      type: "boolean"
    },
    description: "Tells the title whether or not to use the internal padding defined by the visualization in it's positioning. For example, d3plus-plot will add padding on the left so that the title appears centered above the x-axis. By default, this padding is only applied on screens larger than 600 pixels wide.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "boolean | function"
    }
  },
  toCanvas: {
    control: {},
    description: "",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "unknown"
    }
  },
  tooltip: {
    control: {
      type: "boolean"
    },
    description: "Whether to display tooltips on hover.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "boolean | function"
    }
  },
  tooltipConfig: {
    control: {},
    description: "Configuration object for the tooltip.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "record"
    }
  },
  total: {
    control: {
      type: "text"
    },
    description: "Accessor function or string key for the total value displayed in the visualization.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "string | boolean | function"
    }
  },
  totalConfig: {
    control: {},
    description: "Configuration object for the total bar.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "record"
    }
  },
  totalFormat: {
    control: {},
    description: "Formatter function for the value in the total bar.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "function"
    }
  },
  totalPadding: {
    control: {
      type: "boolean"
    },
    description: "Tells the total whether or not to use the internal padding defined by the visualization in it's positioning. For example, d3plus-plot will add padding on the left so that the total appears centered above the x-axis. By default, this padding is only applied on screens larger than 600 pixels wide.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "boolean | function"
    }
  },
  translate: {
    control: {},
    description: "Defines how informational text strings should be displayed. By default, this function will try to find the string in question (which is the first argument provided to this function) inside of an internally managed translation Object. If you'd like to override to use custom text, simply pass this method your own custom formatting function.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: true,
      summary: "function"
    }
  },
  width: {
    control: {
      type: "number"
    },
    description: "Overall width of the visualization in pixels.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "number"
    }
  },
  zoom: {
    control: {
      type: "boolean"
    },
    defaultValue: true,
    description: "Enables pan/zoom with zoom-control buttons. On by default for every chart.",
    table: {
      defaultValue: {
        summary: "true"
      }
    },
    type: {
      required: false,
      summary: "boolean"
    }
  },
  zoomBrushHandleSize: {
    control: {
      type: "number"
    },
    description: "The pixel stroke-width of the zoom brush area.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "number"
    }
  },
  zoomBrushHandleStyle: {
    control: {},
    description: "An object containing CSS key/value pairs that is used to style the outer handle area of the zoom brush. Passing `false` will remove all default styling.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "false | record"
    }
  },
  zoomBrushSelectionStyle: {
    control: {},
    description: "An object containing CSS key/value pairs that is used to style the inner selection area of the zoom brush. Passing `false` will remove all default styling.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "false | record"
    }
  },
  zoomControlClassName: {
    control: {
      type: "text"
    },
    description: "An additional CSS class name (or space-separated list of class names) applied to each zoom control button, alongside the fixed `zoom-control` / `zoom-in` / `zoom-out` / `zoom-reset` / `zoom-brush` classes. Setting this automatically disables d3plus's built-in inline `zoomControlStyle`/`zoomControlStyleActive`/`zoomControlStyleHover` defaults (as long as you haven't already customized them yourself), so a host page's own button styling — Tailwind, Bootstrap, a design system — applies through the cascade with no other configuration needed.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "string"
    }
  },
  zoomControlIcons: {
    control: {},
    description: "Overrides one or more of the four built-in zoom-control icons (`zoomIn`, `zoomOut`, `zoomReset`, `zoomBrush`), which otherwise render as inline SVGs. Each value is either an HTML string — used as the button's content in place of the built-in icon — or a mount function, `(el: HTMLElement) => void | (() => void)`, called once with the button's reserved icon slot (a 12x12px element) so you can mount anything imperative into it: a React tree (`createRoot(el).render(<Icon/>)`), a Vue app, a canvas sprite, a brand `<img>`. Return a cleanup function from the mount function if there's teardown to do; it runs right before that slot is discarded — which happens whenever the whole button panel's markup regenerates (a `.locale(...)` change, a `zoomControlClassName` change, or the brush toggle switching), not just once per chart.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "partial"
    }
  },
  zoomControlStyle: {
    control: {},
    description: "An object containing CSS key/value pairs that is used to style each zoom control button (`.zoom-in`, `.zoom-out`, `.zoom-reset`, and `.zoom-brush`). Passing `false` will remove all default styling. Automatically skipped (as if `false`) once `.zoomControlClassName(...)` is set, unless you've explicitly customized this yourself.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "false | record"
    }
  },
  zoomControlStyleActive: {
    control: {},
    description: "An object containing CSS key/value pairs that is used to style each zoom control button when active (`.zoom-in`, `.zoom-out`, `.zoom-reset`, and `.zoom-brush`). Passing `false` will remove all default styling. Automatically skipped (as if `false`) once `.zoomControlClassName(...)` is set, unless you've explicitly customized this yourself.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "false | record"
    }
  },
  zoomControlStyleHover: {
    control: {},
    description: "An object containing CSS key/value pairs that is used to style each zoom control button on hover (`.zoom-in`, `.zoom-out`, `.zoom-reset`, and `.zoom-brush`). Passing `false` will remove all default styling. Automatically skipped (as if `false`) once `.zoomControlClassName(...)` is set, unless you've explicitly customized this yourself.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "false | record"
    }
  },
  zoomFactor: {
    control: {
      type: "number"
    },
    defaultValue: 2,
    description: "Multiplier applied to programmatic zoom steps.",
    table: {
      defaultValue: {
        summary: "2"
      }
    },
    type: {
      required: false,
      summary: "number"
    }
  },
  zoomMax: {
    control: {
      type: "number"
    },
    description: "Maximum zoom scale factor. Defaults to the scale at which the smallest shape fills the chart area.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "number"
    }
  },
  zoomPadding: {
    control: {
      type: "number"
    },
    description: "A pixel value to be used to pad all sides of a zoomed area.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "number"
    }
  },
  zoomPan: {
    control: {
      type: "boolean"
    },
    defaultValue: true,
    description: "Whether panning (drag) is enabled while zoomed.",
    table: {
      defaultValue: {
        summary: "true"
      }
    },
    type: {
      required: false,
      summary: "boolean"
    }
  },
  zoomScroll: {
    control: {
      type: "radio"
    },
    defaultValue: "modifier",
    description: "Whether the mouse wheel (and one-finger touch) zooms. `\"modifier\"` (the\ndefault) leaves page scrolling alone: only\nCtrl/⌘ + wheel or a trackpad/two-finger pinch zooms, and one finger pans\nonly once zoomed in. `true` zooms on any wheel; `false` never does.",
    options: [
      "modifier"
    ],
    table: {
      defaultValue: {
        summary: "modifier"
      }
    },
    type: {
      required: false,
      summary: "boolean | \"modifier\""
    }
  }
};
