import fs from "node:fs";
import path from "node:path";
import {fileURLToPath} from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

const escape = str =>
  String(str)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");

const unescape = str =>
  String(str)
    .replace(/&quot;/g, '"')
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&amp;/g, "&");

/**
    Lists every HTML page under a package's `dev/` folder (except the
    generated index and build output), as paths relative to `dev/`.
*/
export function devPages(devDir) {
  const pages = [];
  const walk = rel => {
    for (const entry of fs.readdirSync(path.join(devDir, rel), {
      withFileTypes: true,
    })) {
      const next = rel ? `${rel}/${entry.name}` : entry.name;
      if (entry.isDirectory()) {
        if (entry.name !== "umd" && entry.name !== "node_modules") walk(next);
      } else if (entry.name.endsWith(".html") && next !== "index.html") {
        pages.push(next);
      }
    }
  };
  walk("");
  return pages;
}

/**
    Reads a dev page's `<title>` and `<meta name="description">`.
*/
export function pageMeta(file) {
  const html = fs.readFileSync(file, "utf8");
  const title = html.match(/<title>([^<]*)<\/title>/i);
  const description = html.match(
    /<meta\s+name="description"\s+content="([^"]*)"/i,
  );
  return {
    title: title ? unescape(title[1].trim()) : "",
    description: description ? unescape(description[1].trim()) : "",
  };
}

/**
    Sorts pages by folder, putting a page named after its folder (like
    `charts/Treemap/Treemap.html`) ahead of the folder's other pages.
*/
function comparePages(a, b) {
  const dirA = path.posix.dirname(a);
  const dirB = path.posix.dirname(b);
  if (dirA !== dirB) {
    if (dirA === ".") return -1;
    if (dirB === ".") return 1;
    return dirA.localeCompare(dirB);
  }
  const lead = p =>
    path.posix.basename(p, ".html") ===
    path.posix.basename(path.posix.dirname(p));
  if (lead(a) !== lead(b)) return lead(a) ? -1 : 1;
  return a.localeCompare(b);
}

/**
    Builds the `dev/index.html` landing page for a package, listing every dev
    page grouped by folder with its description.
*/
export function buildIndex(pkgDir) {
  const devDir = path.join(pkgDir, "dev");
  const {name} = JSON.parse(
    fs.readFileSync(path.join(pkgDir, "package.json"), "utf8"),
  );
  const pages = devPages(devDir).sort(comparePages);
  const groups = new Map();
  for (const page of pages) {
    const dir = path.posix.dirname(page);
    if (!groups.has(dir)) groups.set(dir, []);
    groups.get(dir).push(page);
  }
  const sections = [...groups]
    .map(([dir, list]) => {
      const heading =
        dir === "."
          ? ""
          : `\n      <h2>${escape(dir.split("/").join(" / "))}</h2>`;
      const items = list
        .map(page => {
          const {description} = pageMeta(path.join(devDir, page));
          const label = path.posix.basename(page, ".html");
          return `        <li><a href="${escape(page)}">${escape(label)}</a> <span>${escape(description)}</span></li>`;
        })
        .join("\n");
      return `    <section>${heading}\n      <ul>\n${items}\n      </ul>\n    </section>`;
    })
    .join("\n");
  return `<!doctype html>
<!-- Generated by scripts/dev-index.js from each page's <meta name="description">. Do not edit. -->
<html>
  <head>
    <meta charset="utf-8">
    <title>${escape(name)} dev pages</title>
    <style>
      body {
        font: 14px/1.5 sans-serif;
        margin: 2rem auto;
        max-width: 960px;
        padding: 0 1rem;
      }
      h1 {
        font-size: 20px;
      }
      h2 {
        border-bottom: 1px solid #ddd;
        font-size: 15px;
        margin: 1.5rem 0 0.25rem;
      }
      input {
        font-size: 14px;
        padding: 4px 8px;
        width: 320px;
      }
      ul {
        list-style: none;
        margin: 0;
        padding: 0;
      }
      li {
        padding: 2px 0;
      }
      a {
        color: #0366d6;
        font-weight: 600;
        text-decoration: none;
      }
      a:hover {
        text-decoration: underline;
      }
      span {
        color: #555;
      }
    </style>
  </head>
  <body>
    <h1>${escape(name)} dev pages</h1>
    <input id="filter" type="search" placeholder="Filter pages" autofocus>
${sections}
    <script>
      document.getElementById("filter").addEventListener("input", function(e) {
        var q = e.target.value.toLowerCase();
        document.querySelectorAll("li").forEach(function(li) {
          li.hidden = q && li.textContent.toLowerCase().indexOf(q) < 0 && li.querySelector("a").getAttribute("href").toLowerCase().indexOf(q) < 0;
        });
        document.querySelectorAll("section").forEach(function(s) {
          s.hidden = !s.querySelector("li:not([hidden])");
        });
      });
    </script>
  </body>
</html>
`;
}

/**
    Packages whose `dev/` folder is a set of static pages served by
    scripts/dev.js (the Vite-based framework wrappers and docs are skipped).
*/
export function staticDevPackages() {
  const packagesDir = path.join(root, "packages");
  return fs
    .readdirSync(packagesDir)
    .map(name => path.join(packagesDir, name))
    .filter(
      dir =>
        fs.existsSync(path.join(dir, "dev")) &&
        !fs.existsSync(path.join(dir, "vite.config.js")) &&
        path.basename(dir) !== "docs",
    );
}

/**
    Writes a package's `dev/index.html`, only touching the file when its
    content changes. Returns true if it was written.
*/
export function writeIndex(pkgDir) {
  const file = path.join(pkgDir, "dev", "index.html");
  const html = buildIndex(pkgDir);
  if (fs.existsSync(file) && fs.readFileSync(file, "utf8") === html)
    return false;
  fs.writeFileSync(file, html);
  return true;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  for (const dir of staticDevPackages()) {
    if (writeIndex(dir))
      console.log(
        `wrote ${path.relative(root, path.join(dir, "dev", "index.html"))}`,
      );
  }
}
