// WARNING: do not edit this file directly, it is generated dynamically from
// the source JSDOC comments using the npm run docs script.

import React from "react";



export const argTypes = {
  configs: {
    control: {},
    description: "One or more config objects, merged left-to-right (later\nobjects win); `undefined`/`null` entries are ignored.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: true,
      summary: "array.&lt;record | undefined&gt;"
    }
  },
  instance: {
    control: {},
    description: "A d3plus class instance.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: true,
      summary: "d3plusinstance"
    }
  },
  node: {
    control: {},
    description: "The DOM element the visualization renders into (its `select`).",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: true,
      summary: "element"
    }
  }
};
