// WARNING: do not edit this file directly, it is generated dynamically from
// the source JSDOC comments using the npm run docs script.

import React from "react";



export const argTypes = {
  params: {
    control: {
      type: "object"
    },
    description: "Additional parameters.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: true,
      summary: "object"
    }
  },
  "params.condition": {
    control: {
      type: "boolean"
    },
    defaultValue: true,
    description: "Whether or not the element should be rendered (or removed).",
    table: {
      defaultValue: {
        summary: true
      }
    },
    type: {
      required: false,
      summary: "boolean"
    }
  },
  "params.duration": {
    control: {
      type: "number"
    },
    defaultValue: 0,
    description: "The duration for the d3 transition.",
    table: {
      defaultValue: {
        summary: 0
      }
    },
    type: {
      required: false,
      summary: "number"
    }
  },
  "params.enter": {
    control: {
      type: "object"
    },
    defaultValue: "{}",
    description: "A collection of key/value pairs that map to attributes to be given on enter.",
    table: {
      defaultValue: {
        summary: "{}"
      }
    },
    type: {
      required: false,
      summary: "object"
    }
  },
  "params.exit": {
    control: {
      type: "object"
    },
    defaultValue: "{}",
    description: "A collection of key/value pairs that map to attributes to be given on exit.",
    table: {
      defaultValue: {
        summary: "{}"
      }
    },
    type: {
      required: false,
      summary: "object"
    }
  },
  "params.parent": {
    control: {},
    defaultValue: "d3.select(\"body\")",
    description: "The parent element for this new element to be appended to.",
    table: {
      defaultValue: {
        summary: "d3.select(\"body\")"
      }
    },
    type: {
      required: false,
      summary: "d3selection"
    }
  },
  "params.update": {
    control: {
      type: "object"
    },
    defaultValue: "{}",
    description: "A collection of key/value pairs that map to attributes to be given on update.",
    table: {
      defaultValue: {
        summary: "{}"
      }
    },
    type: {
      required: false,
      summary: "object"
    }
  },
  selector: {
    control: {
      type: "text"
    },
    description: "A D3 selector, which must include the tagname and a class and/or ID.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: true,
      summary: "string"
    }
  }
};
