// WARNING: do not edit this file directly, it is generated dynamically from
// the source JSDOC comments using the npm run docs script.

import React from "react";



export const argTypes = {
  p: {
    control: {},
    description: "Configuration object with enter, exit, update, and parent options.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "elemparams"
    }
  },
  selector: {
    control: {
      type: "text"
    },
    description: "A CSS selector string for the element tag and classes.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: true,
      summary: "string"
    }
  }
};
