// WARNING: do not edit this file directly, it is generated dynamically from
// the source JSDOC comments using the npm run docs script.

import React from "react";



export const argTypes = {
  font: {
    control: {
      type: "object"
    },
    description: "Can be either a valid CSS font-family string (single or comma-separated names) or an Array of string names.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: true,
      summary: "string | array"
    }
  }
};
