// WARNING: do not edit this file directly, it is generated dynamically from
// the source JSDOC comments using the npm run docs script.

import React from "react";



export const argTypes = {
  e: {
    control: {},
    description: "The d3 selection to apply styles to.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: true,
      summary: "stylable"
    }
  },
  s: {
    control: {},
    defaultValue: "{}",
    description: "An object of key/value style pairs.",
    table: {
      defaultValue: {
        summary: "{}"
      }
    },
    type: {
      required: false,
      summary: "record"
    }
  }
};
