// WARNING: do not edit this file directly, it is generated dynamically from
// the source JSDOC comments using the npm run docs script.

import React from "react";



export const argTypes = {
  style: {
    control: {},
    description: "CSS style properties to apply when measuring.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: false,
      summary: "record"
    }
  },
  text: {
    control: {
      type: "text"
    },
    description: "The text string to measure.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: true,
      summary: "string"
    }
  }
};
