// WARNING: do not edit this file directly, it is generated dynamically from
// the source JSDOC comments using the npm run docs script.

import React from "react";



export const argTypes = {
  locale: {
    control: {
      type: "text"
    },
    defaultValue: "en-US",
    description: "A locale code (e.g. \"en-US\", \"fr-FR\") or an explicit rules object. Defaults to \"en-US\".",
    table: {
      defaultValue: {
        summary: "en-US"
      }
    },
    type: {
      required: false,
      summary: "string | titlecaserules"
    }
  },
  str: {
    control: {
      type: "text"
    },
    description: "The string to capitalize.",
    table: {
      defaultValue: {
        summary: "undefined"
      }
    },
    type: {
      required: true,
      summary: "string | undefined"
    }
  }
};
