import {Axis} from "../components/index.js";
import {assign} from "@d3plus/dom";
import type {DataPoint} from "@d3plus/data";
import {accessor, getProp} from "../utils/index.js";

import {installFluent} from "../fluent.js";
import {applyMatrixLayout, matrixDef} from "./ChartDefinition.js";
import {runChartDraw} from "./runChartDraw.js";
import Viz from "./Viz.js";

// E4: Matrix's identity-coerce accessors.
const matrixSchema = [
  {key: "columnList", coerce: "identity" as const},
  {key: "columnSort", coerce: "identity" as const},
  {key: "rowList", coerce: "identity" as const},
  {key: "rowSort", coerce: "identity" as const},
];

const defaultAxisConfig: Record<string, unknown> = {
  align: "start",
  barConfig: {
    stroke: 0,
  },
  gridSize: 0,
  padding: 5,
  paddingInner: 0,
  paddingOuter: 0,
  scale: "band",
  tickSize: 0,
};

/**
    Creates a simple rows/columns Matrix view of any dataset. See [this example](https://d3plus.org/examples/d3plus-matrix/getting-started/) for help getting started using the Matrix class.
*/
export default class Matrix extends Viz {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  [key: string]: any;

  /**
    Invoked when creating a new class instance, and sets any default parameters.
    @private
  */
  constructor() {
    super();

    // E3: scalar defaults sourced from matrixDef.
    this._cellPadding = matrixDef.defaults.cellPadding as number;

    this._column = matrixDef.defaults.column;
    this._columnAxis = new Axis();
    this._columnConfig = assign({orient: "top"}, defaultAxisConfig);
    // columnSort default — installFluent below seeds via this value when set.
    const columnSortDefault = (
      a: DataPoint[keyof DataPoint],
      b: DataPoint[keyof DataPoint],
    ) => `${a}`.localeCompare(`${b}`);

    this._label = (d: DataPoint, i: number) =>
      `${getProp.bind(this)("row", d, i)} / ${getProp.bind(this)("column", d, i)}`;

    const defaultMouseMoveShape = this._on["mousemove.shape"];
    this._on["mousemove.shape"] = (
      d: DataPoint,
      i: number,
      x: DataPoint,
      event: MouseEvent,
    ) => {
      defaultMouseMoveShape(d, i, x, event);
      const row = getProp.bind(this)("row", d, i);
      const column = getProp.bind(this)("column", d, i);
      this.hover(
        (h: DataPoint, ii: number) =>
          (getProp.bind(this)("row", h, ii) === row ||
          getProp.bind(this)("column", h, ii) === column) && typeof this._colorScale(h, ii) === "number",
      );
    };

    this._row = matrixDef.defaults.row;
    this._rowAxis = new Axis();
    this._rowConfig = assign({orient: "left"}, defaultAxisConfig);
    const rowSortDefault = (
      a: DataPoint[keyof DataPoint],
      b: DataPoint[keyof DataPoint],
    ) => `${a}`.localeCompare(`${b}`);
    // E4: install Matrix's identity-coerce accessors (columnList/columnSort/
    // rowList/rowSort). Defaults for the sorts are the localeCompare functions
    // defined above; columnList/rowList default to undefined (no override).
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    installFluent(this as any, matrixSchema, {
      columnSort: columnSortDefault,
      rowSort: rowSortDefault,
    });
  }

  /**
      Extends the draw behavior of the abstract Viz class.
      @private
  */
  _draw(callback?: () => void): this {
    (super._draw as (...args: unknown[]) => unknown)(callback);
    runChartDraw(this, matrixDef, applyMatrixLayout, v => ({
      x: 0,
      y: v._margin.top,
    }));
    return this;
  }

  /**
      The pixel padding in between each cell.
*/
  cellPadding(_?: number): this | number {
    return arguments.length
      ? ((this._cellPadding = _!), this)
      : this._cellPadding;
  }

  /**
      Determines which key in your data should be used for each column in the matrix. Can be either a String that matches a key used in every data point, or an accessor function that receives a data point and it's index in the data array, and is expected to return it's column value.

@example
function column(d) {
  return d.name;
}
  */
  column(
    _?: string | ((d: DataPoint, i: number) => DataPoint[keyof DataPoint]),
  ): this | string | ((d: DataPoint, i: number) => DataPoint[keyof DataPoint]) {
    return arguments.length
      ? ((this._column = typeof _ === "function" ? _ : accessor(_!)), this)
      : this._column;
  }

  /**
      A pass-through to the underlying [Axis](http://d3plus.org/docs/#Axis) config used for the column labels.
*/
  columnConfig(_?: Record<string, unknown>): this | Record<string, unknown> {
    return arguments.length
      ? ((this._columnConfig = assign(this._columnConfig, _!)), this)
      : this._columnConfig;
  }

  // columnList, columnSort generated by installFluent(matrixSchema).

  /**
      Determines which key in your data should be used for each row in the matrix. Can be either a String that matches a key used in every data point, or an accessor function that receives a data point and it's index in the data array, and is expected to return it's row value.

@example
function row(d) {
  return d.name;
}
  */
  row(
    _?: string | ((d: DataPoint, i: number) => DataPoint[keyof DataPoint]),
  ): this | string | ((d: DataPoint, i: number) => DataPoint[keyof DataPoint]) {
    return arguments.length
      ? ((this._row = typeof _ === "function" ? _ : accessor(_!)), this)
      : this._row;
  }

  /**
      A pass-through to the underlying [Axis](http://d3plus.org/docs/#Axis) config used for the row labels.
*/
  rowConfig(_?: Record<string, unknown>): this | Record<string, unknown> {
    return arguments.length
      ? ((this._rowConfig = assign(this._rowConfig, _!)), this)
      : this._rowConfig;
  }

  // rowList, rowSort generated by installFluent(matrixSchema).
}
