import {min} from "d3-array";
import {arc} from "d3-shape";

import {assign} from "@d3plus/dom";
import type {DataPoint} from "@d3plus/data";
import {installFluent} from "../fluent.js";
import {pieDef} from "./ChartDefinition.js";
import Viz from "./Viz.js";

// E4: Pie's accessor schema. `padAngle`/`padPixel`/`sort` are identity-store;
// `value` uses the "accessor" coerce — string → accessor(key), scalar → constant.
// `innerRadius` is also a simple identity slot. installFluent installs all five
// at construction so the hand-written `arguments.length` overloads can go.
const pieSchema = [
  {key: "innerRadius", coerce: "identity" as const},
  {key: "padAngle", coerce: "identity" as const},
  {key: "padPixel", coerce: "identity" as const},
  {key: "sort", coerce: "identity" as const},
  {key: "value", coerce: "accessor" as const},
];

/**
    Uses the [d3 pie layout](https://github.com/d3/d3-shape#pies) to creates SVG arcs based on an array of data.
*/
export default class Pie extends Viz {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  [key: string]: any;

  /**
      Invoked when creating a new class instance, and sets any default parameters.
      @private
  */
  constructor() {
    super();

    const defaultLegend = this._legend;
    this._legend = (config: Record<string, unknown>, arr: DataPoint[]) => {
      if (arr.length === this._filteredData.length) return false;
      return defaultLegend.bind(this)(config, arr);
    };
    this._legendSort = (a: DataPoint, b: DataPoint) =>
      this._value(b) - this._value(a);

    this._shapeConfig = assign(this._shapeConfig, {
      ariaLabel: (d: DataPoint, i: number) =>
        this._pieData
          ? `${++this._pieData[i].index}. ${this._drawLabel(d, i)}, ${this._value(d, i)}.`
          : "",
      Path: {
        labelConfig: {
          fontResize: true,
        },
      },
    });
    // E3+E4: defaults sourced from pieDef; accessors installed from pieSchema.
    // installFluent seeds `_value` to pieDef.defaults.value and creates the
    // `value()` setter; the subsequent imperative assignments to `_sort` and
    // `_legendSort` use the now-seeded `_value` accessor.
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    installFluent(this as any, pieSchema, {
      innerRadius: pieDef.defaults.innerRadius,
      padPixel: pieDef.defaults.padPixel,
      value: pieDef.defaults.value,
    });
    this._legendSort = (a: DataPoint, b: DataPoint) =>
      this._value(b) - this._value(a);
    this._pie = pieDef.defaults.pie;
    this._sort = (a: DataPoint, b: DataPoint) =>
      this._value(b) - this._value(a);
  }

  /**
      Extends the draw behavior of the abstract Viz class.
      @private
  */
  _draw(callback?: () => void): this {
    (super._draw as (...args: unknown[]) => unknown)(callback);

    const height = this._height - this._margin.top - this._margin.bottom,
      width = this._width - this._margin.left - this._margin.right;

    const outerRadius = min([width, height])! / 2;

    const pieData = (this._pieData = this._pie
      .padAngle(this._padAngle || this._padPixel / outerRadius)
      .sort(this._sort)
      .value(this._value)(this._filteredData));

    pieData.forEach((d: Record<string, unknown>, i: number) => {
      d.__d3plus__ = true;
      d.i = i;
    });

    const arcData = arc()
      .innerRadius(this._innerRadius)
      .outerRadius(outerRadius);

    // Scene cells via `pieDef.emit`. The arc-shape compute is chart-specific;
    // stash it on `viz._arcData` so emit can read it. No more
    // `_shapes.push(new Path()...)` glue.
    this._arcData = arcData;
    this._chartScene = pieDef.emit({viz: this, shapeData: pieData} as any);
    this._chartTransform = {
      x: width / 2 + this._margin.left,
      y: height / 2 + this._margin.top,
    };
    return this;
  }

  /**
      The pixel value, or function that returns a pixel value, that is used as the inner radius of the Pie (creating a Donut).
*/
  innerRadius(_?: number | (() => number)): this | number | (() => number) {
    return arguments.length
      ? ((this._innerRadius = _), this)
      : this._innerRadius;
  }

  // padAngle, padPixel, sort, value, innerRadius — all generated by
  // installFluent(pieSchema) in the constructor. The "accessor" coerce on
  // `value` reproduces the legacy `typeof _ === "function" ? _ : accessor(_)`.
}
