import {assign} from "@d3plus/dom";
import type {DataPoint} from "@d3plus/data";
import {installFluent} from "../fluent.js";
import {applyPieLayout, pieDef} from "./ChartDefinition.js";
import {centerChartTransform} from "./chartGeometry.js";
import {runChartDraw} from "./runChartDraw.js";
import Viz from "./Viz.js";

// E4: Pie's accessor schema. `padAngle`/`padPixel`/`sort` are identity-store;
// `value` uses the "accessor" coerce — string → accessor(key), scalar → constant.
// `innerRadius` is also a simple identity slot. installFluent installs all five
// at construction so the hand-written `arguments.length` overloads can go.
const pieSchema = [
  {key: "innerRadius", coerce: "identity" as const},
  {key: "padAngle", coerce: "identity" as const},
  {key: "padPixel", coerce: "identity" as const},
  {key: "sort", coerce: "identity" as const},
  {key: "value", coerce: "accessor" as const},
];

/**
    Uses the [d3 pie layout](https://github.com/d3/d3-shape#pies) to creates SVG arcs based on an array of data.
*/
export default class Pie extends Viz {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  [key: string]: any;

  /**
      Invoked when creating a new class instance, and sets any default parameters.
      @private
  */
  constructor() {
    super();

    const defaultLegend = this._legend;
    this._legend = (config: Record<string, unknown>, arr: DataPoint[]) => {
      if (arr.length === this._filteredData.length) return false;
      return defaultLegend.bind(this)(config, arr);
    };
    this._legendSort = (a: DataPoint, b: DataPoint) =>
      this._value(b) - this._value(a);

    this._shapeConfig = assign(this._shapeConfig, {
      ariaLabel: (d: DataPoint, i: number) =>
        this._pieData
          ? `${++this._pieData[i].index}. ${this._drawLabel(d, i)}, ${this._value(d, i)}.`
          : "",
      Path: {
        labelConfig: {
          fontResize: true,
        },
      },
    });
    // E3+E4: defaults sourced from pieDef; accessors installed from pieSchema.
    // installFluent seeds `_value` to pieDef.defaults.value and creates the
    // `value()` setter; the subsequent imperative assignments to `_sort` and
    // `_legendSort` use the now-seeded `_value` accessor.
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    installFluent(this as any, pieSchema, {
      innerRadius: pieDef.defaults.innerRadius,
      padPixel: pieDef.defaults.padPixel,
      value: pieDef.defaults.value,
    });
    this._legendSort = (a: DataPoint, b: DataPoint) =>
      this._value(b) - this._value(a);
    this._pie = pieDef.defaults.pie;
    this._sort = (a: DataPoint, b: DataPoint) =>
      this._value(b) - this._value(a);
  }

  /**
      Extends the draw behavior of the abstract Viz class.
      @private
  */
  _draw(callback?: () => void): this {
    (super._draw as (...args: unknown[]) => unknown)(callback);
    runChartDraw(this, pieDef, applyPieLayout, v =>
      centerChartTransform(v, v._pieWidth, v._pieHeight),
    );
    return this;
  }

  // innerRadius, padAngle, padPixel, sort, value — all generated by
  // installFluent(pieSchema) in the constructor.
}
