import {colorContrast} from "@d3plus/color";
import {assign, backgroundColor} from "@d3plus/dom";

import {TextBox} from "../components/index.js";
import {accessor, constant, getProp} from "../utils/index.js";

import {installFluent} from "../fluent.js";
import {applyRadialMatrixLayout, radialMatrixDef} from "./ChartDefinition.js";
import {centerChartTransform} from "./chartGeometry.js";
import {runChartDraw} from "./runChartDraw.js";
import Viz from "./Viz.js";

// E4: RadialMatrix's identity-coerce accessors.
const radialMatrixSchema = [
  {key: "columnList", coerce: "identity" as const},
  {key: "columnSort", coerce: "identity" as const},
  {key: "rowList", coerce: "identity" as const},
  {key: "rowSort", coerce: "identity" as const},
];

/**
    Creates a radial layout of a rows/columns Matrix of any dataset. See [this example](https://d3plus.org/examples/d3plus-matrix/radial-matrix/) for help getting started using the Matrix class.
*/
export default class RadialMatrix extends Viz {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  [key: string]: any;

  /**
    Invoked when creating a new class instance, and sets any default parameters.
    @private
  */
  constructor() {
    super();

    // E3: scalar defaults sourced from radialMatrixDef.
    this._cellPadding = radialMatrixDef.defaults.cellPadding as number;

    this._column = radialMatrixDef.defaults.column;
    this._columnConfig = {
      shapeConfig: {
        labelConfig: {
          fontColor: () => {
            const bg = this._select ? backgroundColor(this._select.node()) : "rgb(255, 255, 255)";
            return colorContrast(bg);
          },
          padding: 5,
          textAnchor: (d: any) =>
            [0, 180].includes(d.angle)
              ? "middle"
              : [2, 3].includes(d.quadrant)
                ? "end"
                : "start",
          verticalAlign: (d: any) =>
            [90, 270].includes(d.angle)
              ? "middle"
              : [2, 1].includes(d.quadrant)
                ? "bottom"
                : "top",
        },
      },
    };
    const columnSortDefault = (a: any, b: any) => `${a}`.localeCompare(`${b}`);
    this._innerRadius = (radius: any) => radius / 5;

    this._label = (d: any, i: any) =>
      `${getProp.bind(this)("row", d, i)} / ${getProp.bind(this)("column", d, i)}`;

    const defaultMouseMoveShape = this._on["mousemove.shape"];
    this._on["mousemove.shape"] = (d: any, i: any, x: any, event: any) => {
      defaultMouseMoveShape(d, i, x, event);
      const row = getProp.bind(this)("row", d, i);
      const column = getProp.bind(this)("column", d, i);
      this.hover(
        (h, ii) =>
          getProp.bind(this)("row", h, ii) === row ||
          getProp.bind(this)("column", h, ii) === column,
      );
    };

    this._row = radialMatrixDef.defaults.row;
    const rowSortDefault = (a: any, b: any) => `${a}`.localeCompare(`${b}`);

    this._columnLabels = new TextBox();

    // E4: install RadialMatrix's identity-coerce accessors with localeCompare
    // defaults for the sorts.
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    installFluent(this as any, radialMatrixSchema, {
      columnSort: columnSortDefault,
      rowSort: rowSortDefault,
    });
  }

  /**
      Extends the draw behavior of the abstract Viz class.
      @private
  */
  _draw(callback?: () => void) {
    (super._draw as (...args: unknown[]) => unknown)(callback);
    runChartDraw(this, radialMatrixDef, applyRadialMatrixLayout, v =>
      centerChartTransform(v, v._radialMatrixWidth, v._radialMatrixHeight),
    );
    return this;
  }

  /**
      The pixel padding in between each cell.
*/
  cellPadding(_: any) {
    return arguments.length
      ? ((this._cellPadding = _), this)
      : this._cellPadding;
  }

  /**
      Determines which key in your data should be used for each column in the matrix. Can be either a String that matches a key used in every data point, or an accessor function that receives a data point and it's index in the data array, and is expected to return it's column value.

@example
function column(d) {
  return d.name;
}
  */
  column(_: any) {
    return arguments.length
      ? ((this._column = typeof _ === "function" ? _ : accessor(_)), this)
      : this._column;
  }

  /**
      A pass-through to the underlying [Axis](http://d3plus.org/docs/#Axis) config used for the column labels.
*/
  columnConfig(_: any) {
    return arguments.length
      ? ((this._columnConfig = assign(this._columnConfig, _)), this)
      : this._columnConfig;
  }

  /**
      A manual list of IDs to be used for rows.
*/
  // columnList() generated by installFluent(radialMatrixSchema).

  /**
      A sort comparator function that is run on the unique set of column values.

@example
function column(a, b) {
  return a.localeCompare(b);
}
  */
  // columnSort() generated by installFluent(radialMatrixSchema).

  /**
      The radius (in pixels) for the inner donut hole of the diagram. Can either be a static Number, or an accessor function that receives the outer radius as it's only argument.

@example
function(outerRadius) {
  return outerRadius / 5;
}
  */
  innerRadius(_: any) {
    return arguments.length
      ? ((this._innerRadius = typeof _ === "function" ? _ : constant(_)), this)
      : this._innerRadius;
  }

  /**
      Determines which key in your data should be used for each row in the matrix. Can be either a String that matches a key used in every data point, or an accessor function that receives a data point and it's index in the data array, and is expected to return it's row value.

@example
function row(d) {
  return d.name;
}
  */
  row(_: any) {
    return arguments.length
      ? ((this._row = typeof _ === "function" ? _ : accessor(_)), this)
      : this._row;
  }

  /**
      A manual list of IDs to be used for rows.
*/
  // rowList() generated by installFluent(radialMatrixSchema).

  /**
      A sort comparator function that is run on the unique set of row values.

@example
function row(a, b) {
  return a.localeCompare(b);
}
  */
  // rowSort() generated by installFluent(radialMatrixSchema).
}
