import {colorContrast, colorDefaults} from "@d3plus/color";
import {assign, backgroundColor} from "@d3plus/dom";
import {constant} from "../utils/index.js";
import {legendLabel} from "./legendLabel.js";

import {installFluent} from "../fluent.js";
import {applyTreeLayout, treeDef} from "./ChartDefinition.js";
import {runStages} from "./stages.js";
import Viz from "./Viz.js";

// E4: Tree's identity-coerce accessors.
const treeSchema = [
  {key: "orient", coerce: "identity" as const},
  {key: "separation", coerce: "identity" as const},
];

/**
    Uses d3's [tree layout](https://github.com/d3/d3-hierarchy#tree) to create a tidy tree chart based on an array of data.
*/
export default class Tree extends Viz {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  [key: string]: any;

  /**
      Invoked when creating a new class instance, and sets any default parameters.
      @private
*/
  constructor() {
    super();

    // E3+E4: scalar defaults from treeDef + accessor methods from
    // installFluent(treeSchema). The default `separation` function is
    // seeded via the same call.
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    installFluent(this as any, treeSchema, {
      orient: treeDef.defaults.orient,
      separation: (a: any, b: any) => (a.parent === b.parent ? 1 : 2),
    });

    this._legendTooltip = assign(this._legendTooltip, {
      title: legendLabel.bind(this),
    });
    this._previousShapes = [];

    this._shape = treeDef.defaults.shape;
    this._shapeConfig = assign(this._shapeConfig, {
      ariaLabel: (d: any, i: any) =>
        this._treeData
          ? `${this._treeData[i].depth}. ${this._drawLabel(d, i)}.`
          : "",
      labelConfig: {
        fontColor: () => {
          const bg = this._select ? backgroundColor(this._select.node()) : "rgb(255, 255, 255)";
          return colorContrast(bg);
        },
      },
      Path: {
        fill: "none",
        stroke: colorDefaults.missing,
        strokeWidth: 2,
      },
      r: constant(7),
      width: constant(12),
      height: constant(12),
    });

    this._tooltipConfig = assign(this._tooltipConfig, {
      title: (d: any, i: any, x: any) => this._drawLabel(d, i, x.depth - 1),
    });

    this._tree = treeDef.defaults.tree;
  }

  /**
      Extends the draw behavior of the abstract Viz class.
      @private
*/
  _draw(callback?: () => void) {
    (super._draw as (...args: unknown[]) => unknown)(callback);

    // Tree-specific layout (d3-hierarchy tree + label measure + link
    // descriptors + per-shape grouping) runs as `applyTreeLayout` on
    // `treeDef.stages`. The stage writes `_treeData`/`_labelHeight`/
    // `_labelWidths`/`_treeCtx`/`_previousShapes` back onto the viz; emit
    // consumes `_treeCtx` and produces the SceneNodes.
    runStages({viz: this} as any, [applyTreeLayout]);
    this._chartScene = treeDef.emit({viz: this} as any);
    this._chartTransform = {x: this._margin.left, y: this._margin.top};

    return this;
  }

  /**
      Changes the orientation of the entire Tree, either "vertical" (top to bottom) or "horizontal" (left to right).
*/
  // orient() generated by installFluent(treeSchema).

  /**
      The separation function between neighboring nodes.

From the [d3-hierarchy documentation](https://github.com/d3/d3-hierarchy#tree_separation):
> The separation accessor is used to separate neighboring nodes. The separation function is passed two nodes a and b, and must return the desired separation. The nodes are typically siblings, though the nodes may be more distantly related if the layout decides to place such nodes adjacent.

@example
function separation(a, b) {
  return a.parent === b.parent ? 1 : 2;
}
*/
  // separation() generated by installFluent(treeSchema).
}
