/**
    @module globalKeys
    The set of `window` members d3plus (and its d3 dependencies) read off the
    global scope while rendering. `installDom` mirrors each of these from the
    headless `window` onto `globalThis` for the duration of a render, then
    restores the originals.

    This list is the runtime counterpart of the proven test harness in
    `@d3plus/core`'s `test/jsdom.js` — keeping the two in sync means anything the
    test suite exercises headlessly also works through `@d3plus/ssr`.
*/

/** DOM interface constructors (jsdom's `lib/jsdom/living/index.js`). */
const LIVING_KEYS: string[] = [
  "DOMParser",
  "DOMException",
  "NamedNodeMap",
  "Attr",
  "Node",
  "Element",
  "DocumentFragment",
  "HTMLDocument",
  "Document",
  "CharacterData",
  "Comment",
  "DocumentType",
  "DOMImplementation",
  "ProcessingInstruction",
  "Image",
  "Text",
  "Event",
  "CustomEvent",
  "MessageEvent",
  "ErrorEvent",
  "HashChangeEvent",
  "PopStateEvent",
  "UIEvent",
  "MouseEvent",
  "KeyboardEvent",
  "TouchEvent",
  "ProgressEvent",
  "EventTarget",
  "Location",
  "History",
  "HTMLElement",
  "HTMLAnchorElement",
  "HTMLAppletElement",
  "HTMLAreaElement",
  "HTMLAudioElement",
  "HTMLBaseElement",
  "HTMLBodyElement",
  "HTMLBRElement",
  "HTMLButtonElement",
  "HTMLCanvasElement",
  "HTMLDataElement",
  "HTMLDataListElement",
  "HTMLDialogElement",
  "HTMLDirectoryElement",
  "HTMLDivElement",
  "HTMLDListElement",
  "HTMLEmbedElement",
  "HTMLFieldSetElement",
  "HTMLFontElement",
  "HTMLFormElement",
  "HTMLFrameElement",
  "HTMLFrameSetElement",
  "HTMLHeadingElement",
  "HTMLHeadElement",
  "HTMLHRElement",
  "HTMLHtmlElement",
  "HTMLIFrameElement",
  "HTMLImageElement",
  "HTMLInputElement",
  "HTMLLabelElement",
  "HTMLLegendElement",
  "HTMLLIElement",
  "HTMLLinkElement",
  "HTMLMapElement",
  "HTMLMediaElement",
  "HTMLMenuElement",
  "HTMLMetaElement",
  "HTMLMeterElement",
  "HTMLModElement",
  "HTMLObjectElement",
  "HTMLOListElement",
  "HTMLOptGroupElement",
  "HTMLOptionElement",
  "HTMLOutputElement",
  "HTMLParagraphElement",
  "HTMLParamElement",
  "HTMLPreElement",
  "HTMLProgressElement",
  "HTMLQuoteElement",
  "HTMLScriptElement",
  "HTMLSelectElement",
  "HTMLSourceElement",
  "HTMLSpanElement",
  "HTMLStyleElement",
  "HTMLTableCaptionElement",
  "HTMLTableCellElement",
  "HTMLTableColElement",
  "HTMLTableDataCellElement",
  "HTMLTableElement",
  "HTMLTableHeaderCellElement",
  "HTMLTimeElement",
  "HTMLTitleElement",
  "HTMLTableRowElement",
  "HTMLTableSectionElement",
  "HTMLTemplateElement",
  "HTMLTextAreaElement",
  "HTMLTrackElement",
  "HTMLUListElement",
  "HTMLUnknownElement",
  "HTMLVideoElement",
  "SVGElement",
  "SVGGraphicsElement",
  "SVGSVGElement",
  "StyleSheet",
  "MediaList",
  "CSSStyleSheet",
  "CSSRule",
  "CSSStyleRule",
  "CSSMediaRule",
  "CSSImportRule",
  "CSSStyleDeclaration",
  "StyleSheetList",
  "XMLSerializer",
  "XPathException",
  "XPathExpression",
  "XPathResult",
  "XPathEvaluator",
  "HTMLCollection",
  "NodeFilter",
  "NodeIterator",
  "NodeList",
  "Blob",
  "File",
  "FileList",
  "FormData",
  "DOMTokenList",
  "URL",
];

/** Non-constructor `window` members some code paths read directly. */
const OTHER_KEYS: string[] = [
  "addEventListener",
  "atob",
  "btoa",
  "dispatchEvent",
  "getComputedStyle",
  "innerHeight",
  "innerWidth",
  "location",
  "name",
  "removeEventListener",
  "screen",
  "self",
];

/** Deduplicated union of every `window` key `installDom` mirrors. */
export const GLOBAL_KEYS: string[] = [...new Set([...LIVING_KEYS, ...OTHER_KEYS])];
