name: Deploy Storybook to Github Pages

on:
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/deploy-storybook.yml"
      - "packages/docs/**"
      
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
    - uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
      with:
        install_command: yarn install # default: npm ci
        build_command: npm run build -w @d3plus/docs # default: npm run build-storybook
        path: packages/docs/build # default: dist/storybook
        checkout: false # default: true
