name: Deploy Storybook to Github Pages

on:
  push:
    branches:
      - "main"
      
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    defaults:
      run:
        working-directory: ./docs
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      shell: bash
      run: npm ci
    - name: Build
      shell: bash
      run: npm run build
    - name: Upload
      uses: actions/upload-pages-artifact@v3
      with: 
        path: docs/build
    - id: deploy
      name: Deploy
      uses: actions/deploy-pages@v4
      with:
        token: ${{ github.token }}
