on:
  push:
    branches:
      - "main"

defaults:
 run:
  working-directory: ./docs
      
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.build-publish.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - id: build-publish
      uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
      with:
        path: build
        install_command: npm ci
        build_command: npm run build
